// ui/angular/src/navigation/Breadcrumbs.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
} from '@angular/core';

/**
 * Breadcrumbs — Standalone Angular component.
 *
 * @example
 * ```html
 * <ui-breadcrumbs separator="/">
 *   <a href="/">Home</a>
 *   <a href="/products">Products</a>
 *   <span>Current</span>
 * </ui-breadcrumbs>
 * ```
 */
@Component({
  selector: 'ui-breadcrumbs',
  standalone: true,
  imports: [],
  template: `
    <nav class="ui-breadcrumbs" aria-label="Breadcrumb">
      <ng-content />
    </nav>
  `,
  styles: [`
    :host { display: block; }
    .ui-breadcrumbs {
      display: flex;
      align-items: center;
      font-size: var(--ui-text-sm, 0.875rem);
      color: var(--ui-color-text-secondary, #64748b);
      flex-wrap: wrap;
      gap: 0;
    }
    :host ::ng-deep > *:not(:last-child)::after {
      content: var(--ui-breadcrumb-separator, '/');
      margin-inline: var(--ui-space-2, 8px);
      user-select: none;
      color: var(--ui-color-text-secondary);
    }
    :host ::ng-deep > *:last-child {
      color: var(--ui-color-text, #0f172a);
      font-weight: 500;
    }
    :host ::ng-deep a {
      color: inherit;
      text-decoration: none;
    }
    :host ::ng-deep a:hover { text-decoration: underline; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[style.--ui-breadcrumb-separator]': "'\"' + separator() + '\"'",
  },
})
export class Breadcrumbs {
  readonly separator = input('/');
}

// ui/solid/src/navigation/Breadcrumbs.tsx
/**
 * @risklab/ui-solid — Breadcrumbs
 * SolidJS breadcrumbs with separator between children.
 */

import {
  mergeProps,
  splitProps,
  children as resolveChildren,
  For,
  Show,
  type Component,
} from 'solid-js';
import type { BreadcrumbsProps } from '../core/types';

export const Breadcrumbs: Component<BreadcrumbsProps> = (rawProps) => {
  const props = mergeProps({ separator: '/' }, rawProps);
  const [local] = splitProps(props, ['separator', 'children', 'class', 'style']);

  const resolved = resolveChildren(() => local.children);

  const items = () => {
    const c = resolved();
    if (Array.isArray(c)) return c.filter(Boolean);
    if (c != null) return [c];
    return [];
  };

  return (
    <nav
      aria-label="Breadcrumb"
      class={local.class}
      style={{
        display: 'flex',
        'align-items': 'center',
        'font-size': 'var(--ui-text-sm, 0.875rem)',
        color: 'var(--ui-color-text-secondary, #64748b)',
        'font-family': 'var(--ui-font-family, inherit)',
        ...(local.style as Record<string, string> | undefined),
      }}
    >
      <ol
        style={{
          display: 'flex',
          'align-items': 'center',
          'list-style': 'none',
          margin: '0',
          padding: '0',
          'flex-wrap': 'wrap',
          gap: '0',
        }}
      >
        <For each={items()}>
          {(item, i) => (
            <li style={{ display: 'flex', 'align-items': 'center' }}>
              <Show when={i() > 0}>
                <span
                  style={{
                    'margin-inline': 'var(--ui-space-2, 0.5rem)',
                    'user-select': 'none',
                  }}
                  aria-hidden="true"
                >
                  {local.separator}
                </span>
              </Show>
              {item}
            </li>
          )}
        </For>
      </ol>
    </nav>
  );
};
