// ui/svelte/src/navigation/Drawer.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    open = $bindable(false),
    anchor = 'left' as 'left' | 'right' | 'top' | 'bottom',
    size = '280px',
    overlay = true,
    children,
  }: {
    open?: boolean;
    anchor?: 'left' | 'right' | 'top' | 'bottom';
    size?: string;
    overlay?: boolean;
    children?: Snippet;
  } = $props();

  let sizeVar = $derived(
    anchor === 'left' || anchor === 'right' ? `--ui-drawer-w: ${size}` : `--ui-drawer-h: ${size}`
  );

  function handleBackdrop() {
    open = false;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      open = false;
    }
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="ui-drawer-container"
  data-open={open || undefined}
  onkeydown={handleKeydown}
>
  {#if overlay}
    <button type="button" class="ui-drawer-backdrop" aria-label="Close drawer" onclick={handleBackdrop}></button>
  {/if}
  <div
    class="ui-drawer ui-drawer--{anchor}"
    data-open={open || undefined}
    style={sizeVar}
    role="dialog"
    aria-hidden={!open}
    inert={!open || undefined}
  >
    {@render children?.()}
  </div>
</div>

<style>
  .ui-drawer-container {
    position: fixed;
    inset: 0;
    z-index: var(--ui-z-drawer, 1200);
    pointer-events: none;
  }
  .ui-drawer-container[data-open] { pointer-events: auto; }
  .ui-drawer-backdrop {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    opacity: 0;
    transition: opacity var(--ui-transition-base, 250ms);
    border: 0;
    padding: 0;
  }
  .ui-drawer-container[data-open] .ui-drawer-backdrop { opacity: 1; }

  .ui-drawer {
    position: fixed;
    background: var(--ui-color-surface, #fff);
    box-shadow: var(--ui-shadow-xl);
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    transition: transform var(--ui-transition-base, 250ms);
    z-index: 1;
  }
  .ui-drawer--left   { top: 0; left: 0; bottom: 0; width: var(--ui-drawer-w, 280px); transform: translateX(-100%); }
  .ui-drawer--right  { top: 0; right: 0; bottom: 0; width: var(--ui-drawer-w, 280px); transform: translateX(100%); }
  .ui-drawer--top    { top: 0; left: 0; right: 0; height: var(--ui-drawer-h, 320px); transform: translateY(-100%); }
  .ui-drawer--bottom { bottom: 0; left: 0; right: 0; height: var(--ui-drawer-h, 320px); transform: translateY(100%); }
  .ui-drawer--left[data-open],
  .ui-drawer--right[data-open]  { transform: translateX(0); }
  .ui-drawer--top[data-open],
  .ui-drawer--bottom[data-open] { transform: translateY(0); }
</style>

// ui/solid/src/navigation/Drawer.tsx
/**
 * @risklab/ui-solid — Drawer
 * SolidJS drawer using Portal with slide animation via CSS.
 */

import { mergeProps, splitProps, Show, createEffect, onCleanup, type Component } from 'solid-js';
import { Portal } from 'solid-js/web';
import type { DrawerProps } from '../core/types';

export const Drawer: Component<DrawerProps> = (rawProps) => {
  const props = mergeProps(
    {
      open: false,
      anchor: 'left' as const,
      size: '280px',
      overlay: true,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'open',
    'onClose',
    'anchor',
    'size',
    'overlay',
    'children',
    'class',
    'style',
  ]);

  const drawerStyle = (): Record<string, string> => {
    const base: Record<string, string> = {
      position: 'fixed',
      'background-color': 'var(--ui-color-surface, #fff)',
      'box-shadow': 'var(--ui-shadow-xl)',
      'overflow-y': 'auto',
      display: 'flex',
      'flex-direction': 'column',
      transition: 'transform var(--ui-transition-base, 250ms)',
      'z-index': '1',
      'box-sizing': 'border-box',
    };

    const isOpen = local.open;
    switch (local.anchor) {
      case 'left':
        base.top = '0'; base.left = '0'; base.bottom = '0';
        base.width = local.size;
        base.transform = isOpen ? 'translateX(0)' : 'translateX(-100%)';
        break;
      case 'right':
        base.top = '0'; base.right = '0'; base.bottom = '0';
        base.width = local.size;
        base.transform = isOpen ? 'translateX(0)' : 'translateX(100%)';
        break;
      case 'top':
        base.top = '0'; base.left = '0'; base.right = '0';
        base.height = local.size;
        base.transform = isOpen ? 'translateY(0)' : 'translateY(-100%)';
        break;
      case 'bottom':
        base.bottom = '0'; base.left = '0'; base.right = '0';
        base.height = local.size;
        base.transform = isOpen ? 'translateY(0)' : 'translateY(100%)';
        break;
    }

    return base;
  };

  createEffect(() => {
    if (local.open) {
      const onKeyDown = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          local.onClose?.();
        }
      };
      document.addEventListener('keydown', onKeyDown);
      onCleanup(() => document.removeEventListener('keydown', onKeyDown));
    }
  });

  return (
    <Portal>
      <Show when={local.open}>
        <div
          style={{
            position: 'fixed',
            inset: '0',
            'z-index': 'var(--ui-z-drawer, 1200)',
            'pointer-events': 'auto',
          }}
        >
          {/* Backdrop */}
          <Show when={local.overlay}>
            <div
              onClick={() => local.onClose?.()}
              style={{
                position: 'absolute',
                inset: '0',
                'background-color': 'rgba(0, 0, 0, 0.5)',
                opacity: '1',
                transition: 'opacity var(--ui-transition-base, 250ms)',
              }}
            />
          </Show>
          {/* Drawer panel */}
          <div
            class={local.class}
            style={{
              ...drawerStyle(),
              ...(local.style as Record<string, string> | undefined),
            }}
          >
            {local.children}
          </div>
        </div>
      </Show>
    </Portal>
  );
};
