// ui/solid/src/feedback/Progress.tsx
/**
 * @risklab/ui-solid — Progress
 * SolidJS progress (linear & circular) with Show for type switching.
 */

import { mergeProps, splitProps, Show, type Component } from 'solid-js';
import type { ProgressProps } from '../core/types';
import { colorVar } from '../core/tokens';

export const Progress: Component<ProgressProps> = (rawProps) => {
  const props = mergeProps(
    {
      value: 0,
      variant: 'determinate' as const,
      type: 'linear' as const,
      size: 'md' as const,
      color: 'primary' as const,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'value',
    'variant',
    'type',
    'size',
    'color',
    'class',
    'style',
  ]);

  const trackHeight = (): string => {
    const m: Record<string, string> = { xs: '2px', sm: '3px', md: '4px', lg: '6px', xl: '8px' };
    return m[local.size] ?? '4px';
  };

  const circularSize = (): string => {
    const m: Record<string, string> = { xs: '24px', sm: '32px', md: '40px', lg: '56px', xl: '72px' };
    return m[local.size] ?? '40px';
  };

  const clampedValue = () => Math.min(100, Math.max(0, local.value));

  const cv = () => colorVar(local.color);

  // Circular SVG calculations
  const strokeWidth = 4;
  const radius = () => {
    const sz = parseInt(circularSize(), 10);
    return (sz - strokeWidth) / 2;
  };
  const circumference = () => 2 * Math.PI * radius();
  const dashOffset = () =>
    local.variant === 'indeterminate'
      ? circumference() * 0.75
      : circumference() * (1 - clampedValue() / 100);

  return (
    <Show
      when={local.type === 'linear'}
      fallback={
        /* Circular progress */
        <svg
          class={local.class}
          width={circularSize()}
          height={circularSize()}
          viewBox={`0 0 ${parseInt(circularSize(), 10)} ${parseInt(circularSize(), 10)}`}
          style={{
            display: 'inline-block',
            color: cv(),
            ...(local.variant === 'indeterminate'
              ? { animation: 'ui-spin 1.4s linear infinite' }
              : {}),
            ...(local.style as Record<string, string> | undefined),
          }}
          role="progressbar"
          aria-valuenow={local.variant === 'determinate' ? clampedValue() : undefined}
          aria-valuemin={0}
          aria-valuemax={100}
        >
          {/* Background track */}
          <circle
            cx={parseInt(circularSize(), 10) / 2}
            cy={parseInt(circularSize(), 10) / 2}
            r={radius()}
            fill="none"
            stroke="rgba(0,0,0,0.08)"
            stroke-width={strokeWidth}
          />
          {/* Progress arc */}
          <circle
            cx={parseInt(circularSize(), 10) / 2}
            cy={parseInt(circularSize(), 10) / 2}
            r={radius()}
            fill="none"
            stroke="currentColor"
            stroke-width={strokeWidth}
            stroke-dasharray={`${circumference()}`}
            stroke-dashoffset={dashOffset()}
            stroke-linecap="round"
            style={{
              transition: local.variant === 'determinate' ? 'stroke-dashoffset 0.3s ease' : 'none',
              'transform-origin': 'center',
              transform: 'rotate(-90deg)',
            }}
          />
        </svg>
      }
    >
      {/* Linear progress */}
      <div
        class={local.class}
        role="progressbar"
        aria-valuenow={local.variant === 'determinate' ? clampedValue() : undefined}
        aria-valuemin={0}
        aria-valuemax={100}
        style={{
          position: 'relative',
          overflow: 'hidden',
          display: 'block',
          width: '100%',
          'background-color': 'rgba(0,0,0,0.08)',
          'border-radius': '4px',
          height: trackHeight(),
          ...(local.style as Record<string, string> | undefined),
        }}
      >
        <Show
          when={local.variant === 'determinate'}
          fallback={
            <div
              style={{
                position: 'absolute',
                left: '0',
                top: '0',
                bottom: '0',
                width: '40%',
                'background-color': cv(),
                'border-radius': 'inherit',
                animation: 'ui-progress-indeterminate 2.1s cubic-bezier(0.65,0.815,0.735,0.395) infinite',
              }}
            />
          }
        >
          <div
            style={{
              position: 'absolute',
              left: '0',
              top: '0',
              bottom: '0',
              width: `${clampedValue()}%`,
              'background-color': cv(),
              'border-radius': 'inherit',
              transition: 'width 0.4s linear',
            }}
          />
        </Show>
      </div>
    </Show>
  );
};

// ui/react/src/feedback/Progress.tsx
import React, { forwardRef, type CSSProperties } from 'react';

type XStyle =
  | Record<string, string | number>
  | Array<Record<string, string | number> | false | null | undefined>;

/* -------------------------------------------------------------------------- */
/*  Shared                                                                    */
/* -------------------------------------------------------------------------- */

function resolveXStyle(xstyle: XStyle | undefined): CSSProperties {
  if (!xstyle) return {};
  if (Array.isArray(xstyle)) {
    return Object.assign(
      {},
      ...xstyle.filter((s): s is Record<string, string | number> => !!s),
    ) as CSSProperties;
  }
  return xstyle as CSSProperties;
}

const keyframesId = 'ui-progress-keyframes';

function ensureKeyframes(): void {
  if (typeof document === 'undefined') return;
  if (document.getElementById(keyframesId)) return;
  const styleEl = document.createElement('style');
  styleEl.id = keyframesId;
  styleEl.textContent = `
@keyframes ui-linear-indeterminate-1 {
  0%   { left: -35%; right: 100%; }
  60%  { left: 100%; right: -90%; }
  100% { left: 100%; right: -90%; }
}
@keyframes ui-linear-indeterminate-2 {
  0%   { left: -200%; right: 100%; }
  60%  { left: 107%; right: -8%; }
  100% { left: 107%; right: -8%; }
}
@keyframes ui-circular-rotate {
  0%   { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
@keyframes ui-circular-dash {
  0%   { stroke-dasharray: 1, 200; stroke-dashoffset: 0; }
  50%  { stroke-dasharray: 100, 200; stroke-dashoffset: -15; }
  100% { stroke-dasharray: 100, 200; stroke-dashoffset: -125; }
}
`;
  document.head.appendChild(styleEl);
}

/* -------------------------------------------------------------------------- */
/*  LinearProgress                                                            */
/* -------------------------------------------------------------------------- */

type LinearSize = 'sm' | 'md' | 'lg';
type LinearVariant = 'determinate' | 'indeterminate' | 'buffer';

export interface LinearProgressProps {
  value?: number;
  variant?: LinearVariant;
  color?: string;
  size?: LinearSize;
  valueBuffer?: number;
  className?: string;
  style?: CSSProperties;
  xstyle?: XStyle;
  testId?: string;
}

// Size tokens now in CSS: .ui-linear-progress[data-size]

export const LinearProgress = forwardRef<HTMLDivElement, LinearProgressProps>(
  function LinearProgress(
    {
      value = 0,
      variant = 'indeterminate',
      color,
      size = 'md',
      valueBuffer,
      className,
      style,
      xstyle,
      testId,
    },
    ref,
  ) {
    React.useEffect(() => {
      ensureKeyframes();
    }, []);

    const clampedValue = Math.min(100, Math.max(0, value));
    const resolvedColor = color ?? 'var(--ui-progress-color, #1976d2)';

    const userStyle: CSSProperties | undefined = (xstyle || style)
      ? { ...resolveXStyle(xstyle), ...style }
      : undefined;

    // Merge user style with color custom property
    const mergedStyle: CSSProperties = {
      '--ui-progress-bar-color': resolvedColor,
      ...(variant === 'determinate' || variant === 'buffer' ? { '--ui-progress-bar-width': `${clampedValue}%` } : undefined),
      ...(variant === 'buffer' && valueBuffer !== undefined ? { '--ui-progress-bar-buffer-width': `${Math.min(100, Math.max(0, valueBuffer))}%` } : undefined),
      ...userStyle,
    } as CSSProperties;

    const ariaProps: Record<string, string | number | undefined> = {
      role: 'progressbar',
      'aria-valuemin': 0,
      'aria-valuemax': 100,
    };

    if (variant === 'determinate' || variant === 'buffer') {
      ariaProps['aria-valuenow'] = Math.round(clampedValue);
    }

    return (
      <div
        ref={ref}
        className={['ui-linear-progress', className].filter(Boolean).join(' ')}
        style={mergedStyle}
        data-size={size}
        data-testid={testId}
        {...ariaProps}
      >
        {variant === 'buffer' && (
          <div
            className="ui-linear-progress__bar ui-linear-progress__bar--buffer"
          />
        )}

        {variant === 'determinate' || variant === 'buffer' ? (
          <div
            className="ui-linear-progress__bar ui-linear-progress__bar--determinate"
          />
        ) : (
          <>
            <div className="ui-linear-progress__bar ui-linear-progress__bar--indeterminate-1" />
            <div className="ui-linear-progress__bar ui-linear-progress__bar--indeterminate-2" />
          </>
        )}
      </div>
    );
  },
);

/* -------------------------------------------------------------------------- */
/*  CircularProgress                                                          */
/* -------------------------------------------------------------------------- */

type CircularVariant = 'determinate' | 'indeterminate';

export interface CircularProgressProps {
  value?: number;
  variant?: CircularVariant;
  size?: number;
  thickness?: number;
  color?: string;
  className?: string;
  style?: CSSProperties;
  xstyle?: XStyle;
  testId?: string;
}

export const CircularProgress = forwardRef<SVGSVGElement, CircularProgressProps>(
  function CircularProgress(
    {
      value = 0,
      variant = 'indeterminate',
      size = 40,
      thickness = 3.6,
      color,
      className,
      style,
      xstyle,
      testId,
    },
    ref,
  ) {
    React.useEffect(() => {
      ensureKeyframes();
    }, []);

    const clampedValue = Math.min(100, Math.max(0, value));
    const resolvedColor = color ?? 'var(--ui-progress-color, #1976d2)';
    const viewBoxSize = 44;
    const radius = (viewBoxSize - thickness) / 2;
    const circumference = 2 * Math.PI * radius;

    const isDeterminate = variant === 'determinate';
    const strokeDasharray = isDeterminate ? circumference.toFixed(3) : undefined;
    const strokeDashoffset = isDeterminate
      ? (((100 - clampedValue) / 100) * circumference).toFixed(3)
      : undefined;

    const svgStyle: CSSProperties = {
      '--ui-circular-size': `${size}px`,
      '--ui-progress-bar-color': resolvedColor,
      ...resolveXStyle(xstyle),
      ...style,
    } as CSSProperties;

    const ariaProps: Record<string, string | number | undefined> = {
      role: 'progressbar',
      'aria-valuemin': 0,
      'aria-valuemax': 100,
    };

    if (isDeterminate) {
      ariaProps['aria-valuenow'] = Math.round(clampedValue);
    }

    return (
      <svg
        ref={ref}
        className={['ui-circular-progress', !isDeterminate && 'ui-circular-progress--indeterminate', className].filter(Boolean).join(' ')}
        style={svgStyle}
        viewBox={`${viewBoxSize / 2} ${viewBoxSize / 2} ${viewBoxSize} ${viewBoxSize}`}
        data-testid={testId}
        {...ariaProps}
      >
        <circle
          className={isDeterminate ? 'ui-circular-progress__circle ui-circular-progress__circle--determinate' : 'ui-circular-progress__circle ui-circular-progress__circle--indeterminate'}
          cx={viewBoxSize}
          cy={viewBoxSize}
          r={radius}
          fill="none"
          strokeWidth={thickness}
          strokeDasharray={strokeDasharray}
          strokeDashoffset={strokeDashoffset}
          strokeLinecap="round"
        />
      </svg>
    );
  },
);
