// ui/solid/src/utils/index.ts
/**
 * @risklab/ui-solid — Utilities
 * Signal-based media query, click-outside directive, debounce.
 */

import {
  createSignal,
  onMount,
  onCleanup,
  type Accessor,
} from 'solid-js';

// ─── createMediaQuery ──────────────────────────────────────────────
/**
 * Reactive media query hook. Returns an Accessor<boolean>.
 *
 * @example
 * const isMobile = createMediaQuery('(max-width: 768px)');
 * <Show when={isMobile()}>Mobile!</Show>
 */
export function createMediaQuery(query: string): Accessor<boolean> {
  const [matches, setMatches] = createSignal(false);

  onMount(() => {
    if (typeof window === 'undefined') return;
    const mq = window.matchMedia(query);
    setMatches(mq.matches);
    const handler = (e: MediaQueryListEvent) => setMatches(e.matches);
    mq.addEventListener('change', handler);
    onCleanup(() => mq.removeEventListener('change', handler));
  });

  return matches;
}

// ─── clickOutside ──────────────────────────────────────────────────
/**
 * Solid directive for detecting clicks outside an element.
 *
 * Usage in JSX:
 * ```tsx
 * <div use:clickOutside={() => setOpen(false)}>...</div>
 * ```
 *
 * Note: You must declare `clickOutside` in scope for the directive to work.
 */
export function clickOutside(el: HTMLElement, accessor: () => () => void): void {
  const handler = (e: MouseEvent) => {
    if (!el.contains(e.target as Node)) {
      accessor()();
    }
  };

  document.addEventListener('pointerdown', handler);
  onCleanup(() => document.removeEventListener('pointerdown', handler));
}

// ─── debounce ──────────────────────────────────────────────────────
/**
 * Generic debounce utility.
 *
 * @example
 * const debouncedSearch = debounce((q: string) => search(q), 300);
 */
export function debounce<T extends (...args: any[]) => void>(
  fn: T,
  delay: number,
): (...args: Parameters<T>) => void {
  let timeoutId: ReturnType<typeof setTimeout> | undefined;
  return (...args: Parameters<T>) => {
    if (timeoutId) clearTimeout(timeoutId);
    timeoutId = setTimeout(() => fn(...args), delay);
  };
}

// ui/angular/src/utils/index.ts
import {
  Injectable,
  signal,
  effect,
  DestroyRef,
  inject,
  Directive,
  ElementRef,
  output,
} from '@angular/core';

/* ------------------------------------------------------------------ */
/*  MediaQueryService                                                 */
/* ------------------------------------------------------------------ */

/**
 * MediaQueryService — Injectable Angular service.
 * Returns a reactive signal that tracks a CSS media query.
 *
 * @example
 * ```ts
 * const mq = inject(MediaQueryService);
 * const isMobile = mq.matches('(max-width: 768px)');
 * effect(() => console.log('mobile?', isMobile()));
 * ```
 */
@Injectable({ providedIn: 'root' })
export class MediaQueryService {
  private readonly cache = new Map<string, ReturnType<typeof signal<boolean>>>();

  matches(query: string) {
    const existing = this.cache.get(query);
    if (existing) return existing.asReadonly();

    if (typeof window === 'undefined') {
      const sig = signal(false);
      this.cache.set(query, sig);
      return sig.asReadonly();
    }

    const mql = window.matchMedia(query);
    const sig = signal(mql.matches);

    const handler = (e: MediaQueryListEvent) => sig.set(e.matches);
    mql.addEventListener('change', handler);

    this.cache.set(query, sig);
    return sig.asReadonly();
  }
}

/* ------------------------------------------------------------------ */
/*  ClickOutsideDirective                                             */
/* ------------------------------------------------------------------ */

/**
 * ClickOutsideDirective — Standalone Angular directive.
 * Emits when a click occurs outside the host element.
 *
 * @example
 * ```html
 * <div (uiClickOutside)="close()">Dropdown</div>
 * ```
 */
@Directive({
  selector: '[uiClickOutside]',
  standalone: true,
})
export class ClickOutsideDirective {
  private readonly el = inject(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  readonly uiClickOutside = output<MouseEvent>();

  private listener = (event: MouseEvent) => {
    const target = event.target as Node;
    if (target && !this.el.nativeElement.contains(target)) {
      this.uiClickOutside.emit(event);
    }
  };

  constructor() {
    if (typeof document !== 'undefined') {
      document.addEventListener('click', this.listener, true);
      this.destroyRef.onDestroy(() => {
        document.removeEventListener('click', this.listener, true);
      });
    }
  }
}
