// ui/solid/src/feedback/Dialog.tsx
/**
 * @risklab/ui-solid — Dialog
 * SolidJS modal/dialog using Portal and Show.
 */

import { mergeProps, splitProps, Show, createEffect, onCleanup, type Component } from 'solid-js';
import { Portal } from 'solid-js/web';
import type { DialogProps } from '../core/types';
import { sizeMap } from '../core/tokens';

export const Dialog: Component<DialogProps> = (rawProps) => {
  const props = mergeProps(
    {
      open: false,
      modal: true,
      size: 'md' as const,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'open',
    'onClose',
    'modal',
    'size',
    'children',
    'class',
    'style',
  ]);

  const maxWidth = (): string => {
    const m: Record<string, string> = {
      xs: '320px',
      sm: '440px',
      md: '560px',
      lg: '720px',
      xl: '900px',
    };
    return m[local.size] ?? '560px';
  };

  const handleBackdrop = () => {
    if (local.modal) {
      local.onClose?.();
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      local.onClose?.();
    }
  };

  createEffect(() => {
    if (local.open) {
      const onDocKeyDown = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          local.onClose?.();
        }
      };
      document.addEventListener('keydown', onDocKeyDown);
      onCleanup(() => document.removeEventListener('keydown', onDocKeyDown));
    }
  });

  return (
    <Show when={local.open}>
      <Portal>
        <div
          role="dialog"
          aria-modal={local.modal}
          class={local.class}
          onKeyDown={handleKeyDown}
          style={{
            position: 'fixed',
            inset: '0',
            'z-index': 'var(--ui-z-modal, 1300)',
            display: 'flex',
            'align-items': 'center',
            'justify-content': 'center',
            ...(local.style as Record<string, string> | undefined),
          }}
        >
          {/* Backdrop */}
          <div
            onClick={handleBackdrop}
            style={{
              position: 'absolute',
              inset: '0',
              'background-color': 'rgba(0, 0, 0, 0.5)',
            }}
          />
          {/* Content */}
          <div
            style={{
              position: 'relative',
              'background-color': 'var(--ui-color-surface, #fff)',
              'border-radius': 'var(--ui-radius-lg, 0.75rem)',
              'box-shadow': 'var(--ui-shadow-xl)',
              'max-width': maxWidth(),
              width: '90%',
              'max-height': '85vh',
              overflow: 'auto',
              padding: '1.5rem',
              'box-sizing': 'border-box',
              'font-family': 'var(--ui-font-family, inherit)',
              color: 'var(--ui-color-text)',
              'z-index': '1',
            }}
          >
            {local.children}
          </div>
        </div>
      </Portal>
    </Show>
  );
};

// ui/svelte/src/feedback/Dialog.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { SizeVariant } from '../core/types.js';

  let {
    open = $bindable(false),
    modal = true,
    size = 'md' as SizeVariant,
    children,
  }: {
    open?: boolean;
    modal?: boolean;
    size?: SizeVariant;
    children?: Snippet;
  } = $props();

  function handleBackdrop() {
    if (modal) {
      open = false;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      open = false;
    }
  }

  $effect(() => {
    if (open) {
      window.addEventListener('keydown', handleKeydown);
      return () => window.removeEventListener('keydown', handleKeydown);
    }
  });
</script>

{#if open}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <div
    class="ui-dialog-overlay"
    role="dialog"
    aria-modal={modal}
  >
    <div class="ui-dialog-backdrop" onclick={handleBackdrop}></div>
    <div class="ui-dialog ui-dialog--{size}">
      {@render children?.()}
    </div>
  </div>
{/if}

<style>
  .ui-dialog-overlay {
    position: fixed;
    inset: 0;
    z-index: var(--ui-z-modal, 1300);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 1rem;
  }
  .ui-dialog-backdrop {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
  }
  .ui-dialog {
    position: relative;
    background: var(--ui-color-surface, #fff);
    border-radius: var(--ui-radius-lg, 0.75rem);
    box-shadow: var(--ui-shadow-xl);
    max-height: 90vh;
    overflow-y: auto;
    z-index: 1;
    display: flex;
    flex-direction: column;
  }
  .ui-dialog--xs { width: 320px; }
  .ui-dialog--sm { width: 440px; }
  .ui-dialog--md { width: 560px; }
  .ui-dialog--lg { width: 720px; }
  .ui-dialog--xl { width: 900px; }
</style>
