// ui/svelte/src/layout/Stack.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    direction = 'column' as 'row' | 'column' | 'row-reverse' | 'column-reverse',
    gap = '1rem',
    align = 'stretch',
    justify = 'flex-start',
    wrap = false,
    children,
  }: {
    direction?: 'row' | 'column' | 'row-reverse' | 'column-reverse';
    gap?: string;
    align?: string;
    justify?: string;
    wrap?: boolean;
    children?: Snippet;
  } = $props();
</script>

<div
  class="ui-stack"
  style:flex-direction={direction}
  style:gap={gap}
  style:align-items={align}
  style:justify-content={justify}
  style:flex-wrap={wrap ? 'wrap' : 'nowrap'}
>
  {@render children?.()}
</div>

<style>
  .ui-stack {
    display: flex;
    box-sizing: border-box;
    font-family: var(--ui-font-family, inherit);
  }
</style>

// ui/solid/src/layout/Stack.tsx
/**
 * @risklab/ui-solid — Stack
 * SolidJS flex stack with direction, gap, alignment.
 */

import { mergeProps, splitProps, type Component } from 'solid-js';
import type { StackProps } from '../core/types';

export const Stack: Component<StackProps> = (rawProps) => {
  const props = mergeProps(
    {
      direction: 'column' as const,
      gap: 'var(--ui-space-3, 0.75rem)',
      wrap: false,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'direction',
    'gap',
    'align',
    'justify',
    'wrap',
    'children',
    'class',
    'style',
  ]);

  return (
    <div
      class={local.class}
      style={{
        display: 'flex',
        'flex-direction': local.direction,
        gap: local.gap,
        'align-items': local.align ?? undefined,
        'justify-content': local.justify ?? undefined,
        'flex-wrap': local.wrap ? 'wrap' : 'nowrap',
        'box-sizing': 'border-box',
        ...(local.style as Record<string, string> | undefined),
      }}
    >
      {local.children}
    </div>
  );
};
