// ui/angular/src/navigation/Pagination.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  model,
  computed,
} from '@angular/core';

/**
 * Pagination — Standalone Angular component.
 *
 * @example
 * ```html
 * <ui-pagination [count]="10" [(page)]="currentPage" />
 * ```
 */
@Component({
  selector: 'ui-pagination',
  standalone: true,
  imports: [],
  template: `
    <nav class="ui-pagination" [class]="'ui-pagination--' + size()" aria-label="Pagination">
      <button
        type="button"
        class="ui-pagination__btn"
        [disabled]="page() <= 1"
        (click)="goTo(page() - 1)"
        aria-label="Previous page"
      >&lsaquo;</button>

      @for (item of pages(); track item) {
        @if (item === -1) {
          <span class="ui-pagination__ellipsis">&hellip;</span>
        } @else {
          <button
            type="button"
            class="ui-pagination__btn"
            [class.ui-pagination__btn--active]="item === page()"
            [attr.aria-current]="item === page() ? 'page' : null"
            (click)="goTo(item)"
          >{{ item }}</button>
        }
      }

      <button
        type="button"
        class="ui-pagination__btn"
        [disabled]="page() >= count()"
        (click)="goTo(page() + 1)"
        aria-label="Next page"
      >&rsaquo;</button>
    </nav>
  `,
  styles: [`
    :host { display: block; }
    .ui-pagination {
      display: flex;
      align-items: center;
      gap: var(--ui-space-1, 4px);
    }
    .ui-pagination__btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--ui-color-border, #e2e8f0);
      background: var(--ui-color-surface, #fff);
      color: var(--ui-color-text, #0f172a);
      border-radius: var(--ui-radius-md, 8px);
      cursor: pointer;
      font-weight: 500;
      transition: background 0.15s, border-color 0.15s, color 0.15s;
    }
    .ui-pagination__btn:hover:not(:disabled) {
      background: var(--ui-color-primary-50, #eff6ff);
      border-color: var(--ui-color-primary, #3b82f6);
    }
    .ui-pagination__btn:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }
    .ui-pagination__btn--active {
      background: var(--ui-color-primary, #3b82f6);
      color: #fff;
      border-color: var(--ui-color-primary, #3b82f6);
    }
    .ui-pagination__btn--active:hover:not(:disabled) {
      background: var(--ui-color-primary-600, #2563eb);
    }
    .ui-pagination__ellipsis {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      color: var(--ui-color-text-secondary, #64748b);
      user-select: none;
    }

    /* Sizes */
    .ui-pagination--sm .ui-pagination__btn { min-width: 28px; height: 28px; font-size: 0.75rem; }
    .ui-pagination--sm .ui-pagination__ellipsis { min-width: 28px; height: 28px; font-size: 0.75rem; }
    .ui-pagination--md .ui-pagination__btn { min-width: 36px; height: 36px; font-size: 0.875rem; }
    .ui-pagination--md .ui-pagination__ellipsis { min-width: 36px; height: 36px; font-size: 0.875rem; }
    .ui-pagination--lg .ui-pagination__btn { min-width: 44px; height: 44px; font-size: 1rem; }
    .ui-pagination--lg .ui-pagination__ellipsis { min-width: 44px; height: 44px; font-size: 1rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Pagination {
  readonly page = model(1);
  readonly count = input(1);
  readonly siblingCount = input(1);
  readonly boundaryCount = input(1);
  readonly size = input<'sm' | 'md' | 'lg'>('md');

  readonly pages = computed(() => {
    const total = this.count();
    const current = this.page();
    const sibling = this.siblingCount();
    const boundary = this.boundaryCount();

    if (total <= 7) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }

    const left = new Set<number>();
    const right = new Set<number>();
    const center = new Set<number>();

    for (let i = 1; i <= Math.min(boundary, total); i++) left.add(i);
    for (let i = Math.max(1, total - boundary + 1); i <= total; i++) right.add(i);

    const lo = Math.max(1, current - sibling);
    const hi = Math.min(total, current + sibling);
    for (let i = lo; i <= hi; i++) center.add(i);

    const merged = Array.from(new Set([...left, ...center, ...right])).sort(
      (a, b) => a - b,
    );

    const result: number[] = [];
    let prev = 0;
    for (const p of merged) {
      if (p - prev === 2) {
        result.push(prev + 1);
      } else if (p - prev > 2) {
        result.push(-1); // ellipsis
      }
      result.push(p);
      prev = p;
    }
    return result;
  });

  goTo(p: number): void {
    const clamped = Math.max(1, Math.min(p, this.count()));
    this.page.set(clamped);
  }
}

// ui/svelte/src/navigation/Pagination.svelte
<script lang="ts">
  import type { SizeVariant } from '../core/types.js';

  let {
    count = 1,
    page = $bindable(1),
    siblingCount = 1,
    boundaryCount = 1,
    size = 'md' as SizeVariant,
    onpage,
  }: {
    count?: number;
    page?: number;
    siblingCount?: number;
    boundaryCount?: number;
    size?: SizeVariant;
    onpage?: (page: number) => void;
  } = $props();

  /**
   * Build a list of page numbers to display, with ellipsis as null.
   */
  let pages = $derived.by(() => {
    const total = Math.max(1, count);
    const result: (number | null)[] = [];

    const startBoundary = range(1, Math.min(boundaryCount, total));
    const endBoundary = range(Math.max(total - boundaryCount + 1, boundaryCount + 1), total);
    const siblingStart = Math.max(Math.min(page - siblingCount, total - boundaryCount - siblingCount * 2 - 1), boundaryCount + 2);
    const siblingEnd = Math.min(Math.max(page + siblingCount, boundaryCount + siblingCount * 2 + 2), endBoundary.length > 0 ? endBoundary[0] - 2 : total - 1);

    result.push(...startBoundary);

    if (siblingStart > boundaryCount + 2) {
      result.push(null); // left ellipsis
    } else if (boundaryCount + 1 < total - boundaryCount) {
      // bridge single gap
      for (let i = boundaryCount + 1; i < siblingStart; i++) result.push(i);
    }

    result.push(...range(siblingStart, siblingEnd));

    if (siblingEnd < total - boundaryCount - 1) {
      result.push(null); // right ellipsis
    } else if (total - boundaryCount > boundaryCount) {
      for (let i = siblingEnd + 1; i <= total - boundaryCount; i++) result.push(i);
    }

    result.push(...endBoundary);

    // Deduplicate
    const seen = new Set<string>();
    return result.filter((p) => {
      const key = p === null ? `null-${seen.size}` : String(p);
      if (p !== null && seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  });

  function range(start: number, end: number): number[] {
    const result: number[] = [];
    for (let i = start; i <= end; i++) result.push(i);
    return result;
  }

  function goTo(p: number) {
    page = p;
    onpage?.(p);
  }
</script>

<nav class="ui-pagination ui-pagination--rounded" data-size={size} aria-label="Pagination">
  <button
    class="ui-pagination__btn"
    type="button"
    class:ui-pagination__btn--disabled={page <= 1}
    disabled={page <= 1}
    aria-label="Previous page"
    onclick={() => goTo(page - 1)}
  >
    ‹
  </button>

  {#each pages as p}
    {#if p === null}
      <span class="ui-pagination__ellipsis">…</span>
    {:else}
      <button
        class="ui-pagination__btn"
        type="button"
        class:ui-pagination__btn--active={p === page}
        aria-label="Page {p}"
        aria-current={p === page ? 'page' : undefined}
        onclick={() => goTo(p)}
      >
        {p}
      </button>
    {/if}
  {/each}

  <button
    class="ui-pagination__btn"
    type="button"
    class:ui-pagination__btn--disabled={page >= count}
    disabled={page >= count}
    aria-label="Next page"
    onclick={() => goTo(page + 1)}
  >
    ›
  </button>
</nav>

<style>
  .ui-pagination {
    display: flex;
    align-items: center;
    gap: var(--ui-space-1, 4px);
    font-family: var(--ui-font-family, inherit);
  }
  .ui-pagination__btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border: 1px solid var(--ui-color-border, #e2e8f0);
    cursor: pointer;
    font-weight: 400;
    background: transparent;
    color: var(--ui-color-text, #0f172a);
    width: var(--ui-pagination-btn-size, 36px);
    height: var(--ui-pagination-btn-size, 36px);
    font-size: var(--ui-pagination-font-size, 14px);
    border-radius: var(--ui-radius-md, 8px);
    transition: background-color 150ms;
  }
  .ui-pagination__btn:hover:not(:disabled):not(.ui-pagination__btn--active) {
    background: rgba(0, 0, 0, 0.04);
  }
  .ui-pagination__btn--active {
    border: none;
    color: #fff;
    font-weight: 600;
    background: var(--ui-color-primary, #4f46e5);
  }
  .ui-pagination__btn--disabled { cursor: not-allowed; opacity: 0.4; }
  .ui-pagination__ellipsis {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: var(--ui-pagination-btn-size, 36px);
    height: var(--ui-pagination-btn-size, 36px);
    font-size: var(--ui-pagination-font-size, 14px);
    border: none;
    cursor: default;
    color: var(--ui-color-text, #0f172a);
    background: transparent;
  }

  .ui-pagination[data-size="sm"] { --ui-pagination-btn-size: 28px; --ui-pagination-font-size: 12px; }
  .ui-pagination[data-size="md"] { --ui-pagination-btn-size: 36px; --ui-pagination-font-size: 14px; }
  .ui-pagination[data-size="lg"] { --ui-pagination-btn-size: 44px; --ui-pagination-font-size: 16px; }
</style>
