// ui/angular/src/inputs/Button.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  output,
  computed,
} from '@angular/core';
import type { SizeVariant, ColorVariant } from '../core/types';

/**
 * Button — Standalone Angular component.
 *
 * @example
 * ```html
 * <ui-button variant="filled" size="md" color="primary" (click)="save()">
 *   Save
 * </ui-button>
 * ```
 */
@Component({
  selector: 'ui-button',
  standalone: true,
  imports: [],
  template: `
    <button
      [class]="classes()"
      [type]="type()"
      [disabled]="disabled() || loading()"
      [attr.aria-busy]="loading() || null"
      [attr.aria-disabled]="disabled() || loading() || null"
      (click)="onClick($event)"
    >
      @if (loading()) {
        <svg class="ui-btn__spinner" width="16" height="16" viewBox="0 0 24 24" fill="none">
          <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3" stroke-linecap="round"
                  stroke-dasharray="31.4 31.4" />
        </svg>
      }
      <ng-content />
    </button>
  `,
  styles: [`
    :host { display: inline-flex; }
    :host([fullWidth]) { display: flex; width: 100%; }

    button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 0.5em;
      border: none;
      cursor: pointer;
      font-family: var(--ui-font-family, inherit);
      font-weight: var(--ui-weight-medium, 500);
      line-height: 1;
      white-space: nowrap;
      transition: background-color var(--ui-transition-fast, 150ms),
                  color var(--ui-transition-fast, 150ms),
                  border-color var(--ui-transition-fast, 150ms),
                  opacity var(--ui-transition-fast, 150ms);
      outline: none;
      box-sizing: border-box;
      width: 100%;
    }

    button:focus-visible {
      outline: 2px solid var(--ui-color-primary);
      outline-offset: 2px;
    }

    /* Sizes */
    .ui-btn--xs { height: 1.5rem; padding: 0 0.5rem; font-size: var(--ui-text-xs, 0.75rem); border-radius: var(--ui-radius-sm, 0.25rem); }
    .ui-btn--sm { height: 2rem; padding: 0 0.75rem; font-size: var(--ui-text-sm, 0.875rem); border-radius: var(--ui-radius-sm, 0.25rem); }
    .ui-btn--md { height: 2.5rem; padding: 0 1rem; font-size: var(--ui-text-sm, 0.875rem); border-radius: var(--ui-radius-md, 0.5rem); }
    .ui-btn--lg { height: 3rem; padding: 0 1.5rem; font-size: var(--ui-text-base, 1rem); border-radius: var(--ui-radius-md, 0.5rem); }
    .ui-btn--xl { height: 3.5rem; padding: 0 2rem; font-size: var(--ui-text-lg, 1.125rem); border-radius: var(--ui-radius-lg, 0.75rem); }

    /* Filled */
    .ui-btn--filled { background-color: var(--_btn-bg); color: #fff; border: none; }
    .ui-btn--filled:hover:not(:disabled) { filter: brightness(0.9); }

    /* Outlined */
    .ui-btn--outlined { background: transparent; color: var(--_btn-bg); border: 1px solid var(--_btn-bg); }
    .ui-btn--outlined:hover:not(:disabled) { background: var(--_btn-bg); color: #fff; }

    /* Ghost */
    .ui-btn--ghost { background: transparent; color: var(--_btn-bg); border: none; }
    .ui-btn--ghost:hover:not(:disabled) { background: color-mix(in srgb, var(--_btn-bg) 10%, transparent); }

    /* Link */
    .ui-btn--link { background: transparent; color: var(--_btn-bg); border: none; text-decoration: underline; padding: 0; height: auto; }
    .ui-btn--link:hover:not(:disabled) { opacity: 0.8; }

    /* Colors */
    .ui-btn--primary { --_btn-bg: var(--ui-color-primary, #4f46e5); }
    .ui-btn--secondary { --_btn-bg: var(--ui-color-secondary, #7c3aed); }
    .ui-btn--success { --_btn-bg: var(--ui-color-success, #16a34a); }
    .ui-btn--warning { --_btn-bg: var(--ui-color-warning, #d97706); }
    .ui-btn--error { --_btn-bg: var(--ui-color-error, #dc2626); }
    .ui-btn--info { --_btn-bg: var(--ui-color-info, #2563eb); }
    .ui-btn--neutral { --_btn-bg: var(--ui-color-neutral, #64748b); }

    /* States */
    .ui-btn--disabled { opacity: 0.5; cursor: not-allowed; pointer-events: none; }
    .ui-btn--full { width: 100%; }
    .ui-btn--loading { cursor: wait; }

    .ui-btn__spinner {
      animation: ui-spin 0.75s linear infinite;
      flex-shrink: 0;
    }
    @keyframes ui-spin { to { transform: rotate(360deg); } }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Button {
  readonly variant = input<'filled' | 'outlined' | 'ghost' | 'link'>('filled');
  readonly size = input<SizeVariant>('md');
  readonly color = input<ColorVariant>('primary');
  readonly disabled = input(false);
  readonly loading = input(false);
  readonly fullWidth = input(false);
  readonly type = input<'button' | 'submit' | 'reset'>('button');

  readonly btnClick = output<MouseEvent>();

  protected onClick(event: MouseEvent): void {
    if (!this.disabled() && !this.loading()) {
      this.btnClick.emit(event);
    }
  }

  protected readonly classes = computed(() => {
    const parts = [
      'ui-btn',
      `ui-btn--${this.variant()}`,
      `ui-btn--${this.size()}`,
      `ui-btn--${this.color()}`,
    ];
    if (this.fullWidth()) parts.push('ui-btn--full');
    if (this.disabled() || this.loading()) parts.push('ui-btn--disabled');
    if (this.loading()) parts.push('ui-btn--loading');
    return parts.join(' ');
  });
}

// ui/react/src/inputs/Button.tsx
// @risklab/ui � Button component

import {
  forwardRef,
  type CSSProperties,
  type ElementType,
  type ReactNode,
  type ButtonHTMLAttributes,
  type AnchorHTMLAttributes,
} from 'react';
import type { SizeVariant, ColorVariant, BaseProps } from '../styling/types';
import { cx } from '../styling/cx';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ButtonVariant = 'solid' | 'outlined' | 'ghost' | 'soft' | 'link';

type NativeButtonProps = Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'type' | 'disabled' | 'style' | 'className' | 'color'
>;

type NativeAnchorProps = Omit<
  AnchorHTMLAttributes<HTMLAnchorElement>,
  'type' | 'style' | 'className' | 'color' | keyof ButtonHTMLAttributes<HTMLButtonElement>
>;

export interface ButtonProps extends BaseProps, NativeButtonProps, NativeAnchorProps {
  /** Visual style variant. */
  variant?: ButtonVariant;
  /** Button size. */
  size?: SizeVariant;
  /** Colour scheme. */
  color?: ColorVariant;
  /** Icon placed before children. */
  startIcon?: ReactNode;
  /** Icon placed after children. */
  endIcon?: ReactNode;
  /** Shows a spinner and disables interaction. */
  loading?: boolean;
  /** Disables the button. */
  disabled?: boolean;
  /** Stretches the button to 100 % width. */
  fullWidth?: boolean;
  /** HTML button type � ignored when rendering an anchor. */
  type?: 'button' | 'submit' | 'reset';
  /** If provided, renders as an anchor (`<a>`) element. */
  href?: string;
  /** Polymorphic element type override. */
  as?: ElementType;
  children?: ReactNode;
}

// ---------------------------------------------------------------------------
// Sizing map ? CSS custom properties
// ---------------------------------------------------------------------------

const SIZE_VARS: Record<SizeVariant, CSSProperties> = {
  xs: {
    '--ui-btn-height': '1.5rem',
    '--ui-btn-padding': '0 0.375rem',
    '--ui-btn-font-size': '0.75rem',
    '--ui-btn-radius': '0.25rem',
    '--ui-btn-icon-size': '0.875rem',
  } as CSSProperties,
  sm: {
    '--ui-btn-height': '2rem',
    '--ui-btn-padding': '0 0.625rem',
    '--ui-btn-font-size': '0.8125rem',
    '--ui-btn-radius': '0.3125rem',
    '--ui-btn-icon-size': '1rem',
  } as CSSProperties,
  md: {
    '--ui-btn-height': '2.5rem',
    '--ui-btn-padding': '0 1rem',
    '--ui-btn-font-size': '0.875rem',
    '--ui-btn-radius': '0.375rem',
    '--ui-btn-icon-size': '1.125rem',
  } as CSSProperties,
  lg: {
    '--ui-btn-height': '3rem',
    '--ui-btn-padding': '0 1.5rem',
    '--ui-btn-font-size': '1rem',
    '--ui-btn-radius': '0.5rem',
    '--ui-btn-icon-size': '1.25rem',
  } as CSSProperties,
  xl: {
    '--ui-btn-height': '3.5rem',
    '--ui-btn-padding': '0 2rem',
    '--ui-btn-font-size': '1.125rem',
    '--ui-btn-radius': '0.625rem',
    '--ui-btn-icon-size': '1.5rem',
  } as CSSProperties,
};

// ---------------------------------------------------------------------------
// Color map ? CSS custom properties per variant
// ---------------------------------------------------------------------------

const COLOR_VARS: Record<
  ColorVariant,
  { base: string; contrast: string; soft: string; softFg: string }
> = {
  primary: { base: 'var(--ui-color-primary, #3b82f6)', contrast: '#fff', soft: 'var(--ui-color-primary-soft, #dbeafe)', softFg: 'var(--ui-color-primary, #3b82f6)' },
  secondary: { base: 'var(--ui-color-secondary, #6366f1)', contrast: '#fff', soft: 'var(--ui-color-secondary-soft, #e0e7ff)', softFg: 'var(--ui-color-secondary, #6366f1)' },
  success: { base: 'var(--ui-color-success, #22c55e)', contrast: '#fff', soft: 'var(--ui-color-success-soft, #dcfce7)', softFg: 'var(--ui-color-success, #22c55e)' },
  warning: { base: 'var(--ui-color-warning, #f59e0b)', contrast: '#fff', soft: 'var(--ui-color-warning-soft, #fef3c7)', softFg: 'var(--ui-color-warning, #f59e0b)' },
  error: { base: 'var(--ui-color-error, #ef4444)', contrast: '#fff', soft: 'var(--ui-color-error-soft, #fee2e2)', softFg: 'var(--ui-color-error, #ef4444)' },
  info: { base: 'var(--ui-color-info, #06b6d4)', contrast: '#fff', soft: 'var(--ui-color-info-soft, #cffafe)', softFg: 'var(--ui-color-info, #06b6d4)' },
  neutral: { base: 'var(--ui-color-neutral, #6b7280)', contrast: '#fff', soft: 'var(--ui-color-neutral-soft, #f3f4f6)', softFg: 'var(--ui-color-neutral, #6b7280)' },
};

function variantStyles(variant: ButtonVariant, color: ColorVariant): CSSProperties {
  const c = COLOR_VARS[color];
  switch (variant) {
    case 'solid':
      return {
        '--ui-btn-bg': c.base,
        '--ui-btn-color': c.contrast,
        '--ui-btn-border': 'transparent',
      } as CSSProperties;
    case 'outlined':
      return {
        '--ui-btn-bg': 'transparent',
        '--ui-btn-color': c.base,
        '--ui-btn-border': c.base,
      } as CSSProperties;
    case 'ghost':
      return {
        '--ui-btn-bg': 'transparent',
        '--ui-btn-color': c.base,
        '--ui-btn-border': 'transparent',
      } as CSSProperties;
    case 'soft':
      return {
        '--ui-btn-bg': c.soft,
        '--ui-btn-color': c.softFg,
        '--ui-btn-border': 'transparent',
      } as CSSProperties;
    case 'link':
      return {
        '--ui-btn-bg': 'transparent',
        '--ui-btn-color': c.base,
        '--ui-btn-border': 'transparent',
        '--ui-btn-padding': '0',
        '--ui-btn-height': 'auto',
        textDecoration: 'underline',
      } as CSSProperties;
  }
}

// ---------------------------------------------------------------------------
// Base inline styles
// ---------------------------------------------------------------------------

const baseStyle: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.5em',
  height: 'var(--ui-btn-height)',
  padding: 'var(--ui-btn-padding)',
  fontSize: 'var(--ui-btn-font-size)',
  fontFamily: 'inherit',
  fontWeight: 600,
  lineHeight: 1,
  borderRadius: 'var(--ui-btn-radius)',
  border: '1px solid var(--ui-btn-border, transparent)',
  backgroundColor: 'var(--ui-btn-bg)',
  color: 'var(--ui-btn-color)',
  cursor: 'pointer',
  textDecoration: 'none',
  transition: 'background-color 150ms, color 150ms, border-color 150ms, opacity 150ms',
  outline: 'none',
  userSelect: 'none',
  whiteSpace: 'nowrap',
  boxSizing: 'border-box',
};

const disabledStyle: CSSProperties = {
  opacity: 0.5,
  pointerEvents: 'none',
};

// ---------------------------------------------------------------------------
// Spinner
// ---------------------------------------------------------------------------

function Spinner() {
  return (
    <svg
      aria-hidden="true"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      fill="none"
      className="ui-btn__spinner"
    >
      <circle
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
        strokeDasharray="50 100"
      />
    </svg>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export const Button = forwardRef<HTMLButtonElement | HTMLAnchorElement, ButtonProps>(
  function Button(
    {
      variant = 'solid',
      size = 'md',
      color = 'primary',
      startIcon,
      endIcon,
      loading = false,
      disabled = false,
      fullWidth = false,
      type = 'button',
      href,
      as,
      className,
      style,
      xstyle,
      testId,
      children,
      ...rest
    },
    ref,
  ) {
    const Component: ElementType = as ?? (href ? 'a' : 'button');
    const isDisabled = disabled || loading;

    const resolvedStyle: CSSProperties = {
      ...baseStyle,
      ...SIZE_VARS[size],
      ...variantStyles(variant, color),
      ...(fullWidth ? { width: '100%' } : undefined),
      ...(isDisabled ? disabledStyle : undefined),
      ...(typeof xstyle === 'object' && !Array.isArray(xstyle) ? xstyle : undefined),
      ...(Array.isArray(xstyle)
        ? xstyle.reduce<Record<string, string | number>>(
            (acc, s) => (s ? { ...acc, ...s } : acc),
            {},
          )
        : undefined),
      ...style,
    };

    const elementProps: Record<string, unknown> = {
      ref,
      className: cx('ui-btn', className),
      style: resolvedStyle,
      'data-testid': testId,
      'data-variant': variant,
      'data-size': size,
      'data-color': color,
      'aria-busy': loading || undefined,
      'aria-disabled': isDisabled || undefined,
      ...rest,
    };

    if (Component === 'button') {
      elementProps.type = type;
      elementProps.disabled = isDisabled;
    } else if (Component === 'a') {
      elementProps.href = href;
      elementProps.role = 'button';
      if (isDisabled) {
        elementProps.tabIndex = -1;
        elementProps['aria-disabled'] = true;
      }
    }

    return (
      <Component {...elementProps}>
        {loading ? <Spinner /> : startIcon && <span aria-hidden="true" className="ui-btn__icon">{startIcon}</span>}
        {children}
        {endIcon && !loading && (
          <span aria-hidden="true" className="ui-btn__icon">{endIcon}</span>
        )}
      </Component>
    );
  },
);
