// ui/solid/src/feedback/Toast.tsx
/**
 * @risklab/ui-solid — Toast
 * Context-based toast system: ToastProvider + useToast().
 * ToastContainer rendered via Portal. Uses <For> and <Dynamic>.
 */

import {
  createContext,
  createSignal,
  useContext,
  For,
  Show,
  onCleanup,
  type Component,
  type JSX,
} from 'solid-js';
import { Portal } from 'solid-js/web';
import type { ToastOptions, ToastEntry } from '../core/types';

// ─── Context ──────────────────────────────────────────────────────

export interface ToastAPI {
  show: (options: ToastOptions) => void;
  success: (message: string, duration?: number) => void;
  error: (message: string, duration?: number) => void;
  info: (message: string, duration?: number) => void;
  warning: (message: string, duration?: number) => void;
}

const ToastContext = createContext<ToastAPI>();

export function useToast(): ToastAPI {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error('useToast must be used within a <ToastProvider>');
  return ctx;
}

// ─── Provider ──────────────────────────────────────────────────────

export interface ToastProviderProps {
  children?: JSX.Element;
}

export const ToastProvider: Component<ToastProviderProps> = (props) => {
  let toastIdCounter = 0;
  const timers = new Map<string, ReturnType<typeof setTimeout>>();
  const [toasts, setToasts] = createSignal<ToastEntry[]>([]);

  const removeToast = (id: string) => {
    const timer = timers.get(id);
    if (timer != null) {
      clearTimeout(timer);
      timers.delete(id);
    }
    setToasts((prev) => prev.filter((t) => t.id !== id));
  };

  const show = (options: ToastOptions) => {
    const id = `toast-${++toastIdCounter}`;
    const entry: ToastEntry = { ...options, id };
    setToasts((prev) => [...prev, entry]);
    const duration = options.duration ?? 4000;
    if (duration > 0) {
      const timer = setTimeout(() => removeToast(id), duration);
      timers.set(id, timer);
    }
  };

  onCleanup(() => {
    timers.forEach((timer) => clearTimeout(timer));
    timers.clear();
  });

  const api: ToastAPI = {
    show,
    success: (message, duration) => show({ message, severity: 'success', duration }),
    error: (message, duration) => show({ message, severity: 'error', duration }),
    info: (message, duration) => show({ message, severity: 'info', duration }),
    warning: (message, duration) => show({ message, severity: 'warning', duration }),
  };

  const SEVERITY_COLORS: Record<string, { bg: string; color: string }> = {
    success: { bg: 'var(--ui-color-success, #16a34a)', color: '#fff' },
    info: { bg: 'var(--ui-color-info, #2563eb)', color: '#fff' },
    warning: { bg: 'var(--ui-color-warning, #d97706)', color: '#fff' },
    error: { bg: 'var(--ui-color-error, #dc2626)', color: '#fff' },
  };

  const positionStyle = (pos?: string): Record<string, string> => {
    const base: Record<string, string> = {
      position: 'fixed',
      'z-index': 'var(--ui-z-toast, 1400)',
      display: 'flex',
      'flex-direction': 'column',
      gap: '0.5rem',
      padding: '1rem',
      'pointer-events': 'none',
      'max-width': '420px',
    };
    switch (pos) {
      case 'top-left':
        base.top = '0'; base.left = '0';
        break;
      case 'top-center':
        base.top = '0'; base.left = '50%'; base.transform = 'translateX(-50%)';
        break;
      case 'bottom-left':
        base.bottom = '0'; base.left = '0';
        break;
      case 'bottom-center':
        base.bottom = '0'; base.left = '50%'; base.transform = 'translateX(-50%)';
        break;
      case 'bottom-right':
        base.bottom = '0'; base.right = '0';
        break;
      case 'top-right':
      default:
        base.top = '0'; base.right = '0';
        break;
    }
    return base;
  };

  return (
    <ToastContext.Provider value={api}>
      {props.children}
      <Portal>
        <div style={positionStyle('top-right')}>
          <For each={toasts()}>
            {(toast) => {
              const sc = SEVERITY_COLORS[toast.severity ?? 'info'] ?? SEVERITY_COLORS.info;
              return (
                <div
                  style={{
                    display: 'flex',
                    'align-items': 'center',
                    gap: '0.75rem',
                    'min-width': '288px',
                    padding: '0.75rem 1rem',
                    'border-radius': 'var(--ui-radius-sm, 4px)',
                    'box-shadow': 'var(--ui-shadow-lg)',
                    'background-color': sc.bg,
                    color: sc.color,
                    'font-family': 'var(--ui-font-family, inherit)',
                    'font-size': '0.875rem',
                    'pointer-events': 'auto',
                    animation: 'ui-toast-in 200ms ease forwards',
                  }}
                  role="alert"
                >
                  <span style={{ flex: '1' }}>{toast.message}</span>
                  <button
                    type="button"
                    onClick={() => removeToast(toast.id)}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: 'inherit',
                      cursor: 'pointer',
                      padding: '2px',
                      opacity: '0.8',
                      'font-size': '1rem',
                      'line-height': '1',
                    }}
                    aria-label="Dismiss"
                  >
                    ✕
                  </button>
                </div>
              );
            }}
          </For>
        </div>
      </Portal>
    </ToastContext.Provider>
  );
};

// ui/lit/src/feedback/Toast.ts
import { LitElement, html, css } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { ToastOptions } from '../core/types';

/**
 * `<ui-toast-container>` — Internal container for imperative toasts.
 * Do not use directly — use `UiToast.show()` etc.
 */
@customElement('ui-toast-container')
export class UiToastContainer extends LitElement {
  static styles = css`
    :host {
      position: fixed;
      z-index: var(--ui-z-toast, 1400);
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
      pointer-events: none;
      max-width: 420px;
    }

    :host([position='top-right'])    { top: 1rem; right: 1rem; }
    :host([position='top-left'])     { top: 1rem; left: 1rem; }
    :host([position='bottom-right']) { bottom: 1rem; right: 1rem; }
    :host([position='bottom-left'])  { bottom: 1rem; left: 1rem; }
    :host([position='top-center'])   { top: 1rem; left: 50%; transform: translateX(-50%); }
    :host([position='bottom-center']){ bottom: 1rem; left: 50%; transform: translateX(-50%); }

    .toast {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.75rem 1rem;
      border-radius: var(--ui-radius-md, 0.5rem);
      font-family: var(--ui-font-family, inherit);
      font-size: 0.875rem;
      color: #fff;
      box-shadow: var(--ui-shadow-lg, 0 10px 15px rgba(0,0,0,0.1));
      pointer-events: auto;
      animation: toast-in 200ms ease forwards;
    }

    .toast--exiting {
      animation: toast-out 200ms ease forwards;
    }

    .toast--success { background: var(--ui-color-success, #16a34a); }
    .toast--info    { background: var(--ui-color-info, #2563eb); }
    .toast--warning { background: var(--ui-color-warning, #d97706); }
    .toast--error   { background: var(--ui-color-error, #dc2626); }

    .close-btn {
      background: none;
      border: none;
      color: inherit;
      cursor: pointer;
      padding: 2px;
      opacity: 0.8;
      margin-left: auto;
      flex-shrink: 0;
    }
    .close-btn:hover { opacity: 1; }

    @keyframes toast-in {
      from { opacity: 0; transform: translateY(8px) scale(0.97); }
      to   { opacity: 1; transform: translateY(0) scale(1); }
    }
    @keyframes toast-out {
      from { opacity: 1; transform: translateY(0) scale(1); }
      to   { opacity: 0; transform: translateY(-8px) scale(0.97); }
    }
  `;

  @property({ type: String, reflect: true }) position = 'top-right';

  @state() _toasts: Array<{
    id: number;
    message: string;
    severity: string;
    exiting: boolean;
  }> = [];

  private _nextId = 0;
  private _timers = new Map<number, ReturnType<typeof setTimeout>>();

  disconnectedCallback(): void {
    super.disconnectedCallback();
    for (const timer of this._timers.values()) {
      clearTimeout(timer);
    }
    this._timers.clear();
  }

  addToast(opts: ToastOptions) {
    const id = this._nextId++;
    const severity = opts.severity ?? 'info';
    const duration = opts.duration ?? 4000;
    if (opts.position) this.position = opts.position;

    this._toasts = [...this._toasts, { id, message: opts.message, severity, exiting: false }];

    if (duration > 0) {
      const timer = setTimeout(() => this._dismiss(id), duration);
      this._timers.set(id, timer);
    }
  }

  private _dismiss(id: number) {
    this._timers.delete(id);
    this._toasts = this._toasts.map((t) =>
      t.id === id ? { ...t, exiting: true } : t,
    );
    const exitTimer = setTimeout(() => {
      this._toasts = this._toasts.filter((t) => t.id !== id);
      this._timers.delete(-id);
    }, 220);
    this._timers.set(-id, exitTimer);
  }

  render() {
    return html`
      ${this._toasts.map(
        (t) => html`
          <div class="toast toast--${t.severity} ${t.exiting ? 'toast--exiting' : ''}" role="alert">
            <span>${t.message}</span>
            <button class="close-btn" type="button" aria-label="Close" @click=${() => this._dismiss(t.id)}>✕</button>
          </div>
        `,
      )}
    `;
  }
}

/**
 * Imperative Toast API.
 *
 * @example
 * ```ts
 * import { UiToast } from '@risklab/ui-lit/feedback';
 * UiToast.success('Saved!');
 * UiToast.error('Something failed.');
 * UiToast.show({ message: 'Custom', severity: 'warning', duration: 5000 });
 * ```
 */
export class UiToast {
  private static _container: UiToastContainer | null = null;

  private static _getContainer(): UiToastContainer {
    if (!UiToast._container) {
      UiToast._container = document.createElement('ui-toast-container') as UiToastContainer;
      document.body.appendChild(UiToast._container);
    }
    return UiToast._container;
  }

  static show(opts: ToastOptions): void {
    UiToast._getContainer().addToast(opts);
  }

  static success(message: string, duration?: number): void {
    UiToast.show({ message, severity: 'success', duration });
  }

  static error(message: string, duration?: number): void {
    UiToast.show({ message, severity: 'error', duration });
  }

  static info(message: string, duration?: number): void {
    UiToast.show({ message, severity: 'info', duration });
  }

  static warning(message: string, duration?: number): void {
    UiToast.show({ message, severity: 'warning', duration });
  }

  /** Remove the shared container from the DOM and release the reference. */
  static dispose(): void {
    if (UiToast._container) {
      UiToast._container.remove();
      UiToast._container = null;
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-toast-container': UiToastContainer;
  }
}
