// ui/react/src/workbench/state.tsx
import React, { createContext, useContext, useRef, useSyncExternalStore } from 'react';
import {
  createInitialWorkbenchState,
  createSavedWorkbenchView,
  createWorkbenchStore,
  parseSavedWorkbenchView,
  reduceWorkbenchState,
  serializeSavedWorkbenchView,
  type SavedWorkbenchView,
  type TimeWindow,
  type WorkbenchActions,
  type WorkbenchCompareState,
  type WorkbenchFilterValue,
  type WorkbenchPanelState,
  type WorkbenchSelection,
  type WorkbenchState,
  type WorkbenchStore,
} from './model';

export {
  createInitialWorkbenchState,
  createSavedWorkbenchView,
  createWorkbenchStore,
  parseSavedWorkbenchView,
  reduceWorkbenchState,
  serializeSavedWorkbenchView,
};

export type {
  SavedWorkbenchView,
  TimeWindow,
  WorkbenchAction,
  WorkbenchActions,
  WorkbenchCompareState,
  WorkbenchFilterValue,
  WorkbenchPanelState,
  WorkbenchSelection,
  WorkbenchState,
  WorkbenchStore,
} from './model';

interface WorkbenchContextValue {
  state: WorkbenchState;
  actions: WorkbenchActions;
}

export interface WorkbenchProviderProps {
  children: React.ReactNode;
  initialState?: Partial<WorkbenchState>;
}

const WorkbenchStoreContext = createContext<WorkbenchStore | null>(null);
const fallbackStore = createWorkbenchStore();

export function WorkbenchProvider({ children, initialState }: WorkbenchProviderProps): React.ReactElement {
  const storeRef = useRef<WorkbenchStore | null>(null);
  storeRef.current ??= createWorkbenchStore(initialState);
  return (
    <WorkbenchStoreContext.Provider value={storeRef.current}>
      {children}
    </WorkbenchStoreContext.Provider>
  );
}

function subscribeTo(store: WorkbenchStore, notify: () => void): () => void {
  return store.subscribe(() => notify());
}

export function useWorkbenchSelector<T>(selector: (state: WorkbenchState) => T): T {
  const store = useContext(WorkbenchStoreContext);
  if (!store) throw new Error('[RiskLab UI] useWorkbenchSelector must be used inside <WorkbenchProvider>.');
  return useSyncExternalStore(
    (notify) => subscribeTo(store, notify),
    () => selector(store.getState()),
    () => selector(store.getState()),
  );
}

export function useWorkbenchSelectorOptional<T>(selector: (state: WorkbenchState) => T): T | undefined {
  const contextStore = useContext(WorkbenchStoreContext);
  const store = contextStore ?? fallbackStore;
  const selected = useSyncExternalStore(
    (notify) => contextStore ? subscribeTo(store, notify) : () => undefined,
    () => selector(store.getState()),
    () => selector(store.getState()),
  );
  return contextStore ? selected : undefined;
}

export function useWorkbenchActions(): WorkbenchActions {
  const store = useContext(WorkbenchStoreContext);
  if (!store) throw new Error('[RiskLab UI] useWorkbenchActions must be used inside <WorkbenchProvider>.');
  return store.actions;
}

export function useWorkbenchActionsOptional(): WorkbenchActions | undefined {
  return useContext(WorkbenchStoreContext)?.actions;
}

export function useWorkbench(): WorkbenchContextValue {
  return { state: useWorkbenchSelector((state) => state), actions: useWorkbenchActions() };
}

export function useWorkbenchOptional(): WorkbenchContextValue | null {
  const actions = useWorkbenchActionsOptional();
  const state = useWorkbenchSelectorOptional((current) => current);
  return actions && state ? { state, actions } : null;
}

export function useWorkbenchPanelState(
  panelId: string,
): [WorkbenchPanelState | undefined, (patch: Partial<WorkbenchPanelState>) => void] {
  const panel = useWorkbenchSelector((state) => state.panels[panelId]);
  const actions = useWorkbenchActions();
  return [panel, (patch) => actions.patchPanelState(panelId, patch)];
}

// Re-export these types to keep the established entrypoint complete.
export type WorkbenchStateContracts = {
  timeWindow: TimeWindow;
  compare: WorkbenchCompareState;
  filter: WorkbenchFilterValue;
  selection: WorkbenchSelection;
  savedView: SavedWorkbenchView;
};

// ui/solid/src/workbench/state.tsx
import {
  createContext,
  createMemo,
  createSignal,
  onCleanup,
  useContext,
  type Accessor,
  type Component,
  type JSX,
} from 'solid-js';
import {
  createInitialWorkbenchState,
  createSavedWorkbenchView,
  createWorkbenchStore,
  parseSavedWorkbenchView,
  reduceWorkbenchState,
  serializeSavedWorkbenchView,
  type SavedWorkbenchView,
  type TimeWindow,
  type WorkbenchAction,
  type WorkbenchCompareState,
  type WorkbenchFilterValue,
  type WorkbenchPanelState,
  type WorkbenchSelection,
  type WorkbenchState,
} from './model';

export {
  createInitialWorkbenchState,
  createSavedWorkbenchView,
  createWorkbenchStore,
  parseSavedWorkbenchView,
  reduceWorkbenchState,
  serializeSavedWorkbenchView,
};

export type {
  SavedWorkbenchView,
  TimeWindow,
  WorkbenchAction,
  WorkbenchCompareState,
  WorkbenchFilterValue,
  WorkbenchPanelState,
  WorkbenchSelection,
  WorkbenchState,
} from './model';

export interface WorkbenchContextValue {
  state: Accessor<WorkbenchState>;
  actions: {
    setQuery(query: string): void;
    setFilter(key: string, value: WorkbenchFilterValue | undefined): void;
    setPanelFilter(panelId: string, key: string, value: WorkbenchFilterValue | undefined): void;
    setTimeWindow(timeWindow: TimeWindow | null): void;
    setSelection(selection: WorkbenchSelection | null): void;
    setCompare(compare: Partial<WorkbenchCompareState>): void;
    patchPanelState(panelId: string, patch: Partial<WorkbenchPanelState>): void;
    restoreSavedView(view: SavedWorkbenchView): void;
    reset(state?: Partial<WorkbenchState>): void;
  };
}

export interface WorkbenchProviderProps {
  children?: JSX.Element;
  initialState?: Partial<WorkbenchState>;
}

export const WorkbenchContext = createContext<WorkbenchContextValue>();

export const WorkbenchProvider: Component<WorkbenchProviderProps> = (props) => {
  const store = createWorkbenchStore(props.initialState);
  const [state, setState] = createSignal(store.getState());
  const unsubscribe = store.subscribe((nextState) => {
    setState(() => nextState);
  });

  onCleanup(() => {
    unsubscribe();
  });

  const value: WorkbenchContextValue = {
    state,
    actions: store.actions,
  };

  return (
    <WorkbenchContext.Provider value={value}>
      {props.children}
    </WorkbenchContext.Provider>
  );
};

export function useWorkbench(): WorkbenchContextValue {
  const value = useContext(WorkbenchContext);
  if (!value) {
    throw new Error('[RiskLab UI] useWorkbench must be used inside <WorkbenchProvider>.');
  }
  return value;
}

export function useWorkbenchOptional(): WorkbenchContextValue | null {
  return useContext(WorkbenchContext) ?? null;
}

export function useWorkbenchPanelState(panelId: string) {
  const workbench = useWorkbench();
  return createMemo(() => workbench.state().panels[panelId] ?? {});
}
