// ui/lit/src/navigation/Pagination.ts
import { LitElement, html, css, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { SizeVariant } from '../core/types';

/**
 * `<ui-pagination>` — Page navigation with smart range, ellipsis, prev/next.
 *
 * @fires ui-page - On page change (detail: { page }).
 *
 * @example
 * ```html
 * <ui-pagination count="20" page="3" siblingCount="1" boundaryCount="1" size="md"></ui-pagination>
 * ```
 */
@customElement('ui-pagination')
export class UiPagination extends LitElement {
  static styles = css`
    :host {
      display: flex;
      align-items: center;
      gap: var(--ui-space-1, 4px);
      font-family: var(--ui-font-family, inherit);
    }

    .btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--ui-color-border, #e2e8f0);
      cursor: pointer;
      font-weight: 400;
      background: transparent;
      color: var(--ui-color-text, #0f172a);
      border-radius: var(--ui-radius-md, 0.5rem);
      font-family: inherit;
      transition: all 150ms;
    }

    :host([size='sm']) .btn { width: 28px; height: 28px; font-size: 12px; }
    :host([size='md']) .btn { width: 36px; height: 36px; font-size: 14px; }
    :host([size='lg']) .btn { width: 44px; height: 44px; font-size: 16px; }

    .btn:hover:not(.btn--disabled):not(.btn--active) {
      background: var(--ui-color-surface-variant, #f8fafc);
    }

    .btn--active {
      background: var(--ui-color-primary, #4f46e5);
      color: #fff;
      border-color: var(--ui-color-primary, #4f46e5);
      font-weight: 600;
    }

    .btn--disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }

    .ellipsis {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 36px;
      height: 36px;
      font-size: 14px;
      border: none;
      cursor: default;
      color: var(--ui-color-text, #0f172a);
      background: transparent;
    }
  `;

  @property({ type: Number }) count = 1;
  @property({ type: Number }) page = 1;
  @property({ type: Number }) siblingCount = 1;
  @property({ type: Number }) boundaryCount = 1;
  @property({ type: String, reflect: true }) size: SizeVariant = 'md';

  private get _range(): (number | '...')[] {
    const total = this.count;
    const current = this.page;
    const sibling = this.siblingCount;
    const boundary = this.boundaryCount;

    const totalNumbers = boundary * 2 + sibling * 2 + 3; // boundaries + siblings + current + 2 ellipses
    if (totalNumbers >= total) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }

    const leftSiblingIndex = Math.max(current - sibling, boundary + 1);
    const rightSiblingIndex = Math.min(current + sibling, total - boundary);

    const showLeftDots = leftSiblingIndex > boundary + 2;
    const showRightDots = rightSiblingIndex < total - boundary - 1;

    const result: (number | '...')[] = [];

    // Left boundary
    for (let i = 1; i <= boundary; i++) result.push(i);

    if (showLeftDots) {
      result.push('...');
    } else {
      for (let i = boundary + 1; i < leftSiblingIndex; i++) result.push(i);
    }

    // Siblings + current
    for (let i = leftSiblingIndex; i <= rightSiblingIndex; i++) result.push(i);

    if (showRightDots) {
      result.push('...');
    } else {
      for (let i = rightSiblingIndex + 1; i <= total - boundary; i++) result.push(i);
    }

    // Right boundary
    for (let i = total - boundary + 1; i <= total; i++) result.push(i);

    return result;
  }

  private _goTo(p: number) {
    if (p < 1 || p > this.count || p === this.page) return;
    this.page = p;
    this.dispatchEvent(
      new CustomEvent('ui-page', {
        detail: { page: this.page },
        bubbles: true,
        composed: true,
      }),
    );
  }

  render() {
    return html`
      <button
        type="button"
        class="btn ${this.page <= 1 ? 'btn--disabled' : ''}"
        ?disabled=${this.page <= 1}
        @click=${() => this._goTo(this.page - 1)}
        aria-label="Previous page"
      >‹</button>

      ${this._range.map((item) =>
        item === '...'
          ? html`<span class="ellipsis">…</span>`
          : html`<button
              type="button"
              class="btn ${item === this.page ? 'btn--active' : ''}"
              @click=${() => this._goTo(item as number)}
              aria-current=${item === this.page ? 'page' : nothing}
            >${item}</button>`,
      )}

      <button
        type="button"
        class="btn ${this.page >= this.count ? 'btn--disabled' : ''}"
        ?disabled=${this.page >= this.count}
        @click=${() => this._goTo(this.page + 1)}
        aria-label="Next page"
      >›</button>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-pagination': UiPagination;
  }
}

// ui/angular/src/navigation/Pagination.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  model,
  computed,
} from '@angular/core';

/**
 * Pagination — Standalone Angular component.
 *
 * @example
 * ```html
 * <ui-pagination [count]="10" [(page)]="currentPage" />
 * ```
 */
@Component({
  selector: 'ui-pagination',
  standalone: true,
  imports: [],
  template: `
    <nav class="ui-pagination" [class]="'ui-pagination--' + size()" aria-label="Pagination">
      <button
        type="button"
        class="ui-pagination__btn"
        [disabled]="page() <= 1"
        (click)="goTo(page() - 1)"
        aria-label="Previous page"
      >&lsaquo;</button>

      @for (item of pages(); track item) {
        @if (item === -1) {
          <span class="ui-pagination__ellipsis">&hellip;</span>
        } @else {
          <button
            type="button"
            class="ui-pagination__btn"
            [class.ui-pagination__btn--active]="item === page()"
            [attr.aria-current]="item === page() ? 'page' : null"
            (click)="goTo(item)"
          >{{ item }}</button>
        }
      }

      <button
        type="button"
        class="ui-pagination__btn"
        [disabled]="page() >= count()"
        (click)="goTo(page() + 1)"
        aria-label="Next page"
      >&rsaquo;</button>
    </nav>
  `,
  styles: [`
    :host { display: block; }
    .ui-pagination {
      display: flex;
      align-items: center;
      gap: var(--ui-space-1, 4px);
    }
    .ui-pagination__btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--ui-color-border, #e2e8f0);
      background: var(--ui-color-surface, #fff);
      color: var(--ui-color-text, #0f172a);
      border-radius: var(--ui-radius-md, 8px);
      cursor: pointer;
      font-weight: 500;
      transition: background 0.15s, border-color 0.15s, color 0.15s;
    }
    .ui-pagination__btn:hover:not(:disabled) {
      background: var(--ui-color-primary-50, #eff6ff);
      border-color: var(--ui-color-primary, #3b82f6);
    }
    .ui-pagination__btn:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }
    .ui-pagination__btn--active {
      background: var(--ui-color-primary, #3b82f6);
      color: #fff;
      border-color: var(--ui-color-primary, #3b82f6);
    }
    .ui-pagination__btn--active:hover:not(:disabled) {
      background: var(--ui-color-primary-600, #2563eb);
    }
    .ui-pagination__ellipsis {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      color: var(--ui-color-text-secondary, #64748b);
      user-select: none;
    }

    /* Sizes */
    .ui-pagination--sm .ui-pagination__btn { min-width: 28px; height: 28px; font-size: 0.75rem; }
    .ui-pagination--sm .ui-pagination__ellipsis { min-width: 28px; height: 28px; font-size: 0.75rem; }
    .ui-pagination--md .ui-pagination__btn { min-width: 36px; height: 36px; font-size: 0.875rem; }
    .ui-pagination--md .ui-pagination__ellipsis { min-width: 36px; height: 36px; font-size: 0.875rem; }
    .ui-pagination--lg .ui-pagination__btn { min-width: 44px; height: 44px; font-size: 1rem; }
    .ui-pagination--lg .ui-pagination__ellipsis { min-width: 44px; height: 44px; font-size: 1rem; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Pagination {
  readonly page = model(1);
  readonly count = input(1);
  readonly siblingCount = input(1);
  readonly boundaryCount = input(1);
  readonly size = input<'sm' | 'md' | 'lg'>('md');

  readonly pages = computed(() => {
    const total = this.count();
    const current = this.page();
    const sibling = this.siblingCount();
    const boundary = this.boundaryCount();

    if (total <= 7) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }

    const left = new Set<number>();
    const right = new Set<number>();
    const center = new Set<number>();

    for (let i = 1; i <= Math.min(boundary, total); i++) left.add(i);
    for (let i = Math.max(1, total - boundary + 1); i <= total; i++) right.add(i);

    const lo = Math.max(1, current - sibling);
    const hi = Math.min(total, current + sibling);
    for (let i = lo; i <= hi; i++) center.add(i);

    const merged = Array.from(new Set([...left, ...center, ...right])).sort(
      (a, b) => a - b,
    );

    const result: number[] = [];
    let prev = 0;
    for (const p of merged) {
      if (p - prev === 2) {
        result.push(prev + 1);
      } else if (p - prev > 2) {
        result.push(-1); // ellipsis
      }
      result.push(p);
      prev = p;
    }
    return result;
  });

  goTo(p: number): void {
    const clamped = Math.max(1, Math.min(p, this.count()));
    this.page.set(clamped);
  }
}
