// ui/svelte/src/surfaces/AccordionItem.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import type { Snippet } from 'svelte';

  let {
    value = '',
    disabled = false,
    header,
    children,
  }: {
    value?: string;
    disabled?: boolean;
    header?: Snippet;
    children?: Snippet;
  } = $props();

  const accordion = getContext<{
    value: string[];
    toggle: (v: string) => void;
    isExpanded: (v: string) => boolean;
  }>('ui-accordion');

  let expanded = $derived(accordion.isExpanded(value));

  function handleToggle() {
    if (!disabled) {
      accordion.toggle(value);
    }
  }
</script>

<div class="ui-accordion-item">
  <button
    class="ui-accordion-header"
    type="button"
    class:ui-accordion-header--disabled={disabled}
    {disabled}
    aria-expanded={expanded}
    onclick={handleToggle}
  >
    <span class="ui-accordion-header__title">
      {@render header?.()}
    </span>
    <span
      class="ui-accordion-header__icon"
      class:ui-accordion-header__icon--expanded={expanded}
    >
      <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
        <path d="M4 6L8 10L12 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
  </button>
  {#if expanded}
    <div class="ui-accordion-panel" role="region">
      {@render children?.()}
    </div>
  {/if}
</div>

<style>
  .ui-accordion-item {
    border-bottom: 1px solid var(--ui-color-border, #e2e8f0);
  }
  .ui-accordion-item:last-child { border-bottom: none; }

  .ui-accordion-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    padding: 14px 18px;
    background: var(--ui-color-surface, #fff);
    border: none;
    cursor: pointer;
    color: var(--ui-color-text, #0f172a);
    font-weight: 500;
    font-size: var(--ui-text-sm, 0.875rem);
    text-align: left;
    font-family: var(--ui-font-family, inherit);
  }
  .ui-accordion-header--disabled { cursor: not-allowed; opacity: 0.5; }
  .ui-accordion-header:focus-visible {
    outline: 2px solid var(--ui-color-primary);
    outline-offset: -2px;
  }

  .ui-accordion-header__icon {
    flex-shrink: 0;
    transition: transform 200ms;
    display: inline-flex;
  }
  .ui-accordion-header__icon--expanded { transform: rotate(180deg); }

  .ui-accordion-panel {
    padding: 14px 18px;
    background: var(--ui-color-surface, #fff);
    font-size: var(--ui-text-sm, 0.875rem);
    color: var(--ui-color-text-secondary, #64748b);
  }
</style>

// ui/solid/src/surfaces/AccordionItem.tsx
/**
 * @risklab/ui-solid — AccordionItem
 * SolidJS accordion item consuming AccordionContext. Show/hide panel.
 */

import { mergeProps, splitProps, Show, type Component } from 'solid-js';
import { useAccordionContext } from './Accordion';
import type { AccordionItemProps } from '../core/types';

export const AccordionItem: Component<AccordionItemProps> = (rawProps) => {
  const props = mergeProps({ disabled: false }, rawProps);
  const [local] = splitProps(props, [
    'value',
    'disabled',
    'title',
    'children',
    'class',
    'style',
  ]);

  const ctx = useAccordionContext();

  const isOpen = () => ctx.openItems().includes(local.value);

  const handleToggle = () => {
    if (!local.disabled) {
      ctx.toggle(local.value);
    }
  };

  return (
    <div
      class={local.class}
      style={{
        'border-bottom': '1px solid var(--ui-color-border, #e2e8f0)',
        ...(local.style as Record<string, string> | undefined),
      }}
    >
      <button
        type="button"
        onClick={handleToggle}
        disabled={local.disabled}
        aria-expanded={isOpen()}
        style={{
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          width: '100%',
          padding: '14px 18px',
          background: 'var(--ui-color-surface, #fff)',
          border: 'none',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          color: 'var(--ui-color-text, #0f172a)',
          'font-weight': '500',
          'font-size': 'var(--ui-text-sm, 14px)',
          'text-align': 'left',
          'font-family': 'inherit',
          opacity: local.disabled ? '0.5' : '1',
        }}
      >
        <span>{local.title}</span>
        <span
          style={{
            'flex-shrink': '0',
            transition: 'transform 200ms',
            transform: isOpen() ? 'rotate(180deg)' : 'rotate(0deg)',
          }}
        >
          ▾
        </span>
      </button>
      <Show when={isOpen()}>
        <div
          style={{
            padding: '14px 18px',
            background: 'var(--ui-color-surface, #fff)',
            'font-size': 'var(--ui-text-sm, 14px)',
            color: 'var(--ui-color-text-secondary, #64748b)',
          }}
        >
          {local.children}
        </div>
      </Show>
    </div>
  );
};
