// ui/angular/src/inputs/Slider.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  model,
} from '@angular/core';
import type { SizeVariant, ColorVariant } from '../core/types';

/**
 * Slider — Standalone Angular component with two-way `value` binding.
 *
 * @example
 * ```html
 * <ui-slider [(value)]="volume" [min]="0" [max]="100" [step]="1" color="primary" />
 * ```
 */
@Component({
  selector: 'ui-slider',
  standalone: true,
  imports: [],
  template: `
    <div class="ui-slider" [attr.data-size]="size()" [attr.data-color]="color()">
      <input
        type="range"
        class="ui-slider__input"
        [class.ui-slider__input--disabled]="disabled()"
        [min]="min()"
        [max]="max()"
        [step]="step()"
        [value]="value()"
        [disabled]="disabled()"
        [attr.aria-valuenow]="value()"
        [attr.aria-valuemin]="min()"
        [attr.aria-valuemax]="max()"
        (input)="onInput($event)"
      />
    </div>
  `,
  styles: [`
    :host { display: block; }
    .ui-slider { display: flex; flex-direction: column; gap: 0.25rem; font-family: inherit; position: relative; }

    .ui-slider[data-size="xs"] { --ui-slider-track-h: 2px; --ui-slider-thumb: 12px; }
    .ui-slider[data-size="sm"] { --ui-slider-track-h: 3px; --ui-slider-thumb: 14px; }
    .ui-slider[data-size="md"] { --ui-slider-track-h: 4px; --ui-slider-thumb: 16px; }
    .ui-slider[data-size="lg"] { --ui-slider-track-h: 6px; --ui-slider-thumb: 20px; }
    .ui-slider[data-size="xl"] { --ui-slider-track-h: 8px; --ui-slider-thumb: 24px; }

    .ui-slider[data-color="primary"]   { --ui-slider-color: var(--ui-color-primary, #4f46e5); }
    .ui-slider[data-color="secondary"] { --ui-slider-color: var(--ui-color-secondary, #7c3aed); }
    .ui-slider[data-color="success"]   { --ui-slider-color: var(--ui-color-success, #16a34a); }
    .ui-slider[data-color="warning"]   { --ui-slider-color: var(--ui-color-warning, #d97706); }
    .ui-slider[data-color="error"]     { --ui-slider-color: var(--ui-color-error, #dc2626); }
    .ui-slider[data-color="info"]      { --ui-slider-color: var(--ui-color-info, #2563eb); }
    .ui-slider[data-color="neutral"]   { --ui-slider-color: var(--ui-color-neutral, #64748b); }

    .ui-slider__input {
      width: 100%;
      height: var(--ui-slider-thumb, 16px);
      appearance: none;
      background: transparent;
      cursor: pointer;
      outline: none;
      margin: 0;
      padding: 0;
    }
    .ui-slider__input--disabled { opacity: 0.5; cursor: not-allowed; }

    .ui-slider__input::-webkit-slider-runnable-track {
      height: var(--ui-slider-track-h, 4px);
      background: var(--ui-color-border, #e2e8f0);
      border-radius: 9999px;
    }
    .ui-slider__input::-webkit-slider-thumb {
      appearance: none;
      width: var(--ui-slider-thumb, 16px);
      height: var(--ui-slider-thumb, 16px);
      border-radius: 50%;
      background: var(--ui-slider-color, var(--ui-color-primary));
      border: 2px solid #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,.2);
      margin-top: calc((var(--ui-slider-track-h, 4px) - var(--ui-slider-thumb, 16px)) / 2);
      cursor: pointer;
    }
    .ui-slider__input::-moz-range-track {
      height: var(--ui-slider-track-h, 4px);
      background: var(--ui-color-border, #e2e8f0);
      border-radius: 9999px;
    }
    .ui-slider__input::-moz-range-thumb {
      width: var(--ui-slider-thumb, 16px);
      height: var(--ui-slider-thumb, 16px);
      border-radius: 50%;
      background: var(--ui-slider-color, var(--ui-color-primary));
      border: 2px solid #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,.2);
      cursor: pointer;
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Slider {
  readonly min = input(0);
  readonly max = input(100);
  readonly step = input(1);
  readonly disabled = input(false);
  readonly size = input<SizeVariant>('md');
  readonly color = input<ColorVariant>('primary');

  /** Two-way bound value */
  readonly value = model(0);

  protected onInput(event: Event): void {
    const val = Number((event.target as HTMLInputElement).value);
    this.value.set(val);
  }
}

// ui/solid/src/inputs/Slider.tsx
/**
 * @risklab/ui-solid — Slider
 * SolidJS range slider with size, color, min/max/step.
 */

import { mergeProps, splitProps, type Component, type JSX } from 'solid-js';
import type { SliderProps } from '../core/types';
import { colorVar } from '../core/tokens';

export const Slider: Component<SliderProps> = (rawProps) => {
  const props = mergeProps(
    {
      value: 50,
      min: 0,
      max: 100,
      step: 1,
      disabled: false,
      size: 'md' as const,
      color: 'primary' as const,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'value',
    'onInput',
    'min',
    'max',
    'step',
    'disabled',
    'size',
    'color',
    'class',
    'style',
  ]);

  const thumbSize = (): string => {
    const m: Record<string, string> = { xs: '12px', sm: '14px', md: '16px', lg: '20px', xl: '24px' };
    return m[local.size] ?? '16px';
  };

  const trackH = (): string => {
    const m: Record<string, string> = { xs: '2px', sm: '3px', md: '4px', lg: '6px', xl: '8px' };
    return m[local.size] ?? '4px';
  };

  const handleInput: JSX.EventHandlerUnion<HTMLInputElement, InputEvent> = (e) => {
    local.onInput?.(Number((e.currentTarget as HTMLInputElement).value));
  };

  return (
    <div
      class={local.class}
      style={{
        display: 'flex',
        'flex-direction': 'column',
        gap: '0.25rem',
        'font-family': 'var(--ui-font-family, inherit)',
        ...(local.style as Record<string, string> | undefined),
      }}
    >
      <input
        type="range"
        min={local.min}
        max={local.max}
        step={local.step}
        value={local.value}
        disabled={local.disabled}
        onInput={handleInput}
        style={{
          width: '100%',
          height: thumbSize(),
          appearance: 'none',
          background: 'transparent',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          outline: 'none',
          margin: '0',
          padding: '0',
          opacity: local.disabled ? '0.5' : '1',
          'accent-color': colorVar(local.color),
        }}
      />
    </div>
  );
};
