// ui/angular/src/inputs/Switch.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  model,
} from '@angular/core';
import type { SizeVariant, ColorVariant } from '../core/types';

/**
 * Switch — Standalone Angular component with two-way `checked` binding.
 *
 * @example
 * ```html
 * <ui-switch [(checked)]="darkMode" label="Dark mode" color="primary" />
 * ```
 */
@Component({
  selector: 'ui-switch',
  standalone: true,
  imports: [],
  template: `
    <label
      class="ui-switch"
      [attr.data-size]="size()"
      [attr.data-color]="color()"
      [attr.data-disabled]="disabled()"
    >
      <span class="ui-switch__track" [attr.data-checked]="checked()">
        <span class="ui-switch__thumb" [attr.data-checked]="checked()"></span>
        <input
          type="checkbox"
          class="ui-switch__input"
          role="switch"
          [checked]="checked()"
          [disabled]="disabled()"
          [attr.aria-checked]="checked()"
          (change)="onToggle()"
        />
      </span>
      @if (label()) {
        <span class="ui-switch__text">{{ label() }}</span>
      }
    </label>
  `,
  styles: [`
    :host { display: inline-flex; }
    .ui-switch {
      display: inline-flex;
      align-items: center;
      gap: 0.5em;
      cursor: pointer;
      font-family: var(--ui-font-family, inherit);
      font-size: var(--ui-sw-font-size, 0.875rem);
      user-select: none;
    }
    .ui-switch[data-disabled="true"] { opacity: 0.5; cursor: not-allowed; }

    .ui-switch[data-size="xs"] { --ui-sw-track-w: 1.75rem; --ui-sw-track-h: 1rem;    --ui-sw-thumb: 0.75rem;   --ui-sw-font-size: 0.75rem; }
    .ui-switch[data-size="sm"] { --ui-sw-track-w: 2.25rem; --ui-sw-track-h: 1.25rem; --ui-sw-thumb: 0.9375rem; --ui-sw-font-size: 0.8125rem; }
    .ui-switch[data-size="md"] { --ui-sw-track-w: 2.75rem; --ui-sw-track-h: 1.5rem;  --ui-sw-thumb: 1.125rem;  --ui-sw-font-size: 0.875rem; }
    .ui-switch[data-size="lg"] { --ui-sw-track-w: 3.25rem; --ui-sw-track-h: 1.75rem; --ui-sw-thumb: 1.375rem;  --ui-sw-font-size: 1rem; }
    .ui-switch[data-size="xl"] { --ui-sw-track-w: 3.75rem; --ui-sw-track-h: 2rem;    --ui-sw-thumb: 1.625rem;  --ui-sw-font-size: 1.125rem; }

    .ui-switch[data-color="primary"]   { --ui-sw-active-bg: var(--ui-color-primary, #4f46e5); }
    .ui-switch[data-color="secondary"] { --ui-sw-active-bg: var(--ui-color-secondary, #7c3aed); }
    .ui-switch[data-color="success"]   { --ui-sw-active-bg: var(--ui-color-success, #16a34a); }
    .ui-switch[data-color="warning"]   { --ui-sw-active-bg: var(--ui-color-warning, #d97706); }
    .ui-switch[data-color="error"]     { --ui-sw-active-bg: var(--ui-color-error, #dc2626); }
    .ui-switch[data-color="info"]      { --ui-sw-active-bg: var(--ui-color-info, #2563eb); }
    .ui-switch[data-color="neutral"]   { --ui-sw-active-bg: var(--ui-color-neutral, #64748b); }

    .ui-switch__track {
      position: relative;
      display: inline-flex;
      align-items: center;
      width: var(--ui-sw-track-w, 2.75rem);
      height: var(--ui-sw-track-h, 1.5rem);
      background-color: var(--ui-sw-bg, #d1d5db);
      border-radius: 9999px;
      transition: background-color 200ms;
      flex-shrink: 0;
      box-sizing: border-box;
    }
    .ui-switch__track[data-checked="true"] { background-color: var(--ui-sw-active-bg, var(--ui-color-primary)); }

    .ui-switch__thumb {
      position: absolute;
      width: var(--ui-sw-thumb, 1.125rem);
      height: var(--ui-sw-thumb, 1.125rem);
      border-radius: 50%;
      background-color: #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,0.2);
      transition: transform 200ms;
      left: 2px;
      top: 50%;
      transform: translateY(-50%);
    }
    .ui-switch__thumb[data-checked="true"] {
      transform: translateY(-50%) translateX(calc(var(--ui-sw-track-w, 2.75rem) - var(--ui-sw-thumb, 1.125rem) - 4px));
    }

    .ui-switch__input {
      position: absolute;
      width: 100%;
      height: 100%;
      opacity: 0;
      margin: 0;
      padding: 0;
      cursor: pointer;
      top: 0;
      left: 0;
      z-index: 1;
    }
    .ui-switch__input:disabled { cursor: not-allowed; }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Switch {
  readonly disabled = input(false);
  readonly size = input<SizeVariant>('md');
  readonly color = input<ColorVariant>('primary');
  readonly label = input('');

  /** Two-way bound checked state */
  readonly checked = model(false);

  protected onToggle(): void {
    if (!this.disabled()) {
      this.checked.update(v => !v);
    }
  }
}

// ui/solid/src/inputs/Switch.tsx
/**
 * @risklab/ui-solid — Switch
 * SolidJS toggle switch with size, color, label.
 */

import { mergeProps, splitProps, Show, type Component } from 'solid-js';
import type { SwitchProps } from '../core/types';
import { colorVar } from '../core/tokens';

export const Switch: Component<SwitchProps> = (rawProps) => {
  const props = mergeProps(
    {
      checked: false,
      disabled: false,
      size: 'md' as const,
      color: 'primary' as const,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'checked',
    'onChange',
    'disabled',
    'size',
    'color',
    'label',
    'class',
    'style',
  ]);

  const dims = () => {
    const m: Record<string, { trackW: string; trackH: string; thumb: string; fontSize: string }> = {
      xs: { trackW: '1.75rem', trackH: '1rem', thumb: '0.75rem', fontSize: '0.75rem' },
      sm: { trackW: '2.25rem', trackH: '1.25rem', thumb: '0.9375rem', fontSize: '0.8125rem' },
      md: { trackW: '2.75rem', trackH: '1.5rem', thumb: '1.125rem', fontSize: '0.875rem' },
      lg: { trackW: '3.25rem', trackH: '1.75rem', thumb: '1.375rem', fontSize: '1rem' },
      xl: { trackW: '3.75rem', trackH: '2rem', thumb: '1.625rem', fontSize: '1.125rem' },
    };
    return m[local.size] ?? m.md;
  };

  const handleClick = () => {
    if (!local.disabled) {
      local.onChange?.(!local.checked);
    }
  };

  return (
    <label
      class={local.class}
      style={{
        display: 'inline-flex',
        'align-items': 'center',
        gap: '0.5em',
        cursor: local.disabled ? 'not-allowed' : 'pointer',
        opacity: local.disabled ? '0.5' : '1',
        'font-size': dims().fontSize,
        'font-family': 'var(--ui-font-family, inherit)',
        'user-select': 'none',
        ...(local.style as Record<string, string> | undefined),
      }}
      onClick={(e) => {
        e.preventDefault();
        handleClick();
      }}
    >
      <input
        type="checkbox"
        role="switch"
        checked={local.checked}
        disabled={local.disabled}
        onChange={() => handleClick()}
        aria-checked={local.checked}
        aria-label={local.label ?? undefined}
        style={{
          position: 'absolute',
          width: '1px',
          height: '1px',
          padding: '0',
          margin: '-1px',
          overflow: 'hidden',
          clip: 'rect(0,0,0,0)',
          'white-space': 'nowrap',
          'border-width': '0',
        }}
      />
      <span
        style={{
          position: 'relative',
          display: 'inline-flex',
          'align-items': 'center',
          width: dims().trackW,
          height: dims().trackH,
          'background-color': local.checked ? colorVar(local.color) : '#d1d5db',
          'border-radius': '9999px',
          transition: 'background-color 200ms',
          'flex-shrink': '0',
          'box-sizing': 'border-box',
        }}
      >
        <span
          style={{
            position: 'absolute',
            width: dims().thumb,
            height: dims().thumb,
            'border-radius': '50%',
            'background-color': '#fff',
            'box-shadow': '0 1px 3px rgba(0,0,0,.2)',
            transition: 'transform 200ms',
            left: '2px',
            top: '50%',
            transform: local.checked
              ? `translateY(-50%) translateX(calc(${dims().trackW} - ${dims().thumb} - 4px))`
              : 'translateY(-50%)',
          }}
        />
      </span>
      <Show when={local.label}>
        <span>{local.label}</span>
      </Show>
    </label>
  );
};
