// ui/solid/src/data-display/Badge.tsx
/**
 * @risklab/ui-solid — Badge
 * SolidJS badge component with content, max, dot variant, color.
 */

import { mergeProps, splitProps, Show, type Component } from 'solid-js';
import type { BadgeProps } from '../core/types';
import { colorVar } from '../core/tokens';

export const Badge: Component<BadgeProps> = (rawProps) => {
  const props = mergeProps(
    {
      variant: 'standard' as const,
      color: 'error' as const,
      max: 99,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'content',
    'variant',
    'color',
    'max',
    'children',
    'class',
    'style',
  ]);

  const displayContent = () => {
    if (local.variant === 'dot') return '';
    const val = local.content;
    if (val == null) return '';
    if (typeof val === 'number' && val > local.max) return `${local.max}+`;
    return String(val);
  };

  const isDot = () => local.variant === 'dot';
  const isVisible = () => isDot() || (local.content != null && local.content !== '');

  const indicatorStyle = (): Record<string, string> => {
    const base: Record<string, string> = {
      position: 'absolute',
      display: 'flex',
      'align-items': 'center',
      'justify-content': 'center',
      'box-sizing': 'border-box',
      'font-family': 'var(--ui-font-family, inherit)',
      'font-weight': '600',
      'line-height': '1',
      'white-space': 'nowrap',
      'z-index': '1',
      border: '2px solid #fff',
      top: '0',
      right: '0',
      transform: 'translateX(50%) translateY(-50%)',
      'background-color': colorVar(local.color),
      color: '#fff',
    };
    if (isDot()) {
      base['min-width'] = '0.5rem';
      base.height = '0.5rem';
      base['border-radius'] = '50%';
      base.padding = '0';
      base['font-size'] = '0';
    } else {
      base['min-width'] = '1.25rem';
      base.height = '1.25rem';
      base['font-size'] = '0.75rem';
      base.padding = '0 0.375rem';
      base['border-radius'] = '0.625rem';
    }
    return base;
  };

  return (
    <span
      class={local.class}
      style={{
        position: 'relative',
        display: 'inline-flex',
        'vertical-align': 'middle',
        'flex-shrink': '0',
        ...(local.style as Record<string, string> | undefined),
      }}
    >
      {local.children}
      <Show when={isVisible()}>
        <span style={indicatorStyle()}>
          {displayContent()}
        </span>
      </Show>
    </span>
  );
};

// ui/angular/src/data-display/Badge.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  computed,
} from '@angular/core';
import type { ColorVariant } from '../core/types';

/**
 * Badge — Standalone Angular component wrapping a child element.
 *
 * @example
 * ```html
 * <ui-badge [content]="5" color="error">
 *   <span>🔔</span>
 * </ui-badge>
 * ```
 */
@Component({
  selector: 'ui-badge',
  standalone: true,
  imports: [],
  template: `
    <span class="ui-badge" [attr.data-color]="color()">
      <ng-content />
      @if (variant() === 'dot') {
        <span class="ui-badge__indicator ui-badge__indicator--dot"></span>
      } @else {
        <span class="ui-badge__indicator" [class.ui-badge__indicator--invisible]="!displayValue()">
          {{ displayValue() }}
        </span>
      }
    </span>
  `,
  styles: [`
    :host { display: inline-flex; }
    .ui-badge {
      position: relative;
      display: inline-flex;
      vertical-align: middle;
      flex-shrink: 0;
    }
    .ui-badge__indicator {
      position: absolute;
      display: flex;
      align-items: center;
      justify-content: center;
      box-sizing: border-box;
      font-family: var(--ui-font-family, inherit);
      font-weight: 600;
      line-height: 1;
      white-space: nowrap;
      z-index: 1;
      border: 2px solid var(--ui-badge-outline, #fff);
      min-width: 1.25rem;
      height: 1.25rem;
      font-size: 0.75rem;
      padding: 0 0.375rem;
      border-radius: 0.625rem;
      top: 0;
      right: 0;
      transform: translateX(50%) translateY(-50%);
      background-color: var(--ui-color-error, #ef4444);
      color: #fff;
    }
    .ui-badge__indicator--invisible { display: none; }
    .ui-badge__indicator--dot {
      min-width: 0.5rem;
      height: 0.5rem;
      border-radius: 50%;
      padding: 0;
      font-size: 0;
    }

    [data-color="primary"]   .ui-badge__indicator { background-color: var(--ui-color-primary, #4f46e5); }
    [data-color="secondary"] .ui-badge__indicator { background-color: var(--ui-color-secondary, #7c3aed); }
    [data-color="success"]   .ui-badge__indicator { background-color: var(--ui-color-success, #16a34a); }
    [data-color="warning"]   .ui-badge__indicator { background-color: var(--ui-color-warning, #d97706); }
    [data-color="error"]     .ui-badge__indicator { background-color: var(--ui-color-error, #dc2626); }
    [data-color="info"]      .ui-badge__indicator { background-color: var(--ui-color-info, #2563eb); }
    [data-color="neutral"]   .ui-badge__indicator { background-color: var(--ui-color-neutral, #64748b); }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Badge {
  readonly content = input<string | number | undefined>(undefined);
  readonly variant = input<'standard' | 'dot'>('standard');
  readonly color = input<ColorVariant>('error');
  readonly max = input(99);

  protected readonly displayValue = computed(() => {
    const c = this.content();
    if (c === undefined || c === null || c === '') return '';
    const num = typeof c === 'number' ? c : parseInt(String(c), 10);
    if (!isNaN(num) && num > this.max()) return `${this.max()}+`;
    return String(c);
  });
}
