// ui/solid/src/feedback/Skeleton.tsx
/**
 * @risklab/ui-solid — Skeleton
 * SolidJS skeleton placeholder with variant, width, height, animation.
 */

import { mergeProps, splitProps, Show, type Component } from 'solid-js';
import type { SkeletonProps } from '../core/types';

export const Skeleton: Component<SkeletonProps> = (rawProps) => {
  const props = mergeProps(
    {
      variant: 'text' as const,
      animation: 'pulse' as const,
    },
    rawProps,
  );

  const [local] = splitProps(props, [
    'variant',
    'width',
    'height',
    'animation',
    'class',
    'style',
  ]);

  const skeletonStyle = (): Record<string, string> => {
    const base: Record<string, string> = {
      display: 'block',
      'background-color': 'rgba(0, 0, 0, 0.11)',
    };

    switch (local.variant) {
      case 'text':
        base.height = local.height ?? '1.2em';
        base.width = local.width ?? '100%';
        base['border-radius'] = '4px';
        base['transform-origin'] = '0 55%';
        base.transform = 'scale(1, 0.6)';
        break;
      case 'circular':
        base.width = local.width ?? '40px';
        base.height = local.height ?? '40px';
        base['border-radius'] = '50%';
        break;
      case 'rectangular':
        base.width = local.width ?? '100%';
        base.height = local.height ?? '100px';
        base['border-radius'] = '0';
        break;
      case 'rounded':
        base.width = local.width ?? '100%';
        base.height = local.height ?? '100px';
        base['border-radius'] = '8px';
        break;
    }

    if (local.animation === 'pulse') {
      base.animation = 'ui-pulse 1.5s ease-in-out infinite';
    } else if (local.animation === 'wave') {
      base.overflow = 'hidden';
      base.position = 'relative';
    }

    return base;
  };

  return (
    <span
      class={local.class}
      style={{
        ...skeletonStyle(),
        ...(local.style as Record<string, string> | undefined),
      }}
      aria-hidden="true"
    >
      <Show when={local.animation === 'wave'}>
        <span
          style={{
            position: 'absolute',
            inset: '0',
            animation: 'ui-wave 1.6s linear 0.5s infinite',
            background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent)',
          }}
        />
      </Show>
    </span>
  );
};

// ui/angular/src/feedback/Skeleton.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  computed,
} from '@angular/core';

/**
 * Skeleton — Standalone Angular component for loading placeholders.
 *
 * @example
 * ```html
 * <ui-skeleton variant="text" width="200px" animation="pulse" />
 * <ui-skeleton variant="circular" width="48px" height="48px" animation="wave" />
 * <ui-skeleton variant="rectangular" height="120px" />
 * ```
 */
@Component({
  selector: 'ui-skeleton',
  standalone: true,
  imports: [],
  template: `
    <span [class]="classes()" [style]="styles()" aria-hidden="true">
      @if (animation() === 'wave') {
        <span class="ui-skeleton__inner"></span>
      }
    </span>
  `,
  styles: [`
    :host { display: block; }
    .ui-skeleton {
      display: block;
      background-color: var(--ui-skeleton-bg, rgba(0,0,0,0.11));
    }
    .ui-skeleton--text {
      height: 1.2em;
      border-radius: 4px;
      width: 100%;
      transform-origin: 0 55%;
      transform: scale(1, 0.6);
    }
    .ui-skeleton--circular { border-radius: 50%; }
    .ui-skeleton--rectangular { border-radius: 0; }
    .ui-skeleton--rounded { border-radius: var(--ui-radius-md, 0.5rem); }

    .ui-skeleton--pulse { animation: ui-skeleton-pulse 2s ease-in-out 0.5s infinite; }

    .ui-skeleton--wave { overflow: hidden; position: relative; }
    .ui-skeleton__inner {
      position: absolute;
      inset: 0;
      animation: ui-skeleton-wave 2s linear 0.5s infinite;
      background: linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent);
    }

    @keyframes ui-skeleton-pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.4; }
    }
    @keyframes ui-skeleton-wave {
      0%   { transform: translateX(-100%); }
      100% { transform: translateX(100%); }
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Skeleton {
  readonly variant = input<'text' | 'circular' | 'rectangular' | 'rounded'>('text');
  readonly width = input<string | undefined>(undefined);
  readonly height = input<string | undefined>(undefined);
  readonly animation = input<'pulse' | 'wave' | 'none'>('pulse');

  protected readonly classes = computed(() => {
    const parts = ['ui-skeleton', `ui-skeleton--${this.variant()}`];
    if (this.animation() !== 'none') parts.push(`ui-skeleton--${this.animation()}`);
    return parts.join(' ');
  });

  protected readonly styles = computed(() => {
    const s: string[] = [];
    if (this.width()) s.push(`width:${this.width()}`);
    if (this.height()) s.push(`height:${this.height()}`);
    return s.join(';');
  });
}
