// ui/svelte/src/inputs/TextField.svelte
<script lang="ts">
  import type { SizeVariant } from '../core/types.js';

  let {
    value = $bindable(''),
    variant = 'outlined' as 'outlined' | 'filled' | 'underlined',
    size = 'md' as SizeVariant,
    label = '',
    placeholder = '',
    disabled = false,
    readonly = false,
    error = false,
    helperText = '',
    type = 'text',
    oninput,
    onchange,
  }: {
    value?: string;
    variant?: 'outlined' | 'filled' | 'underlined';
    size?: SizeVariant;
    label?: string;
    placeholder?: string;
    disabled?: boolean;
    readonly?: boolean;
    error?: boolean;
    helperText?: string;
    type?: string;
    oninput?: (e: Event) => void;
    onchange?: (e: Event) => void;
  } = $props();

  const inputId = `ui-tf-${Math.random().toString(36).slice(2, 9)}`;
</script>

<div
  class="ui-textfield"
  data-size={size}
  data-variant={variant}
  data-error={error || undefined}
>
  {#if label}
    <label class="ui-textfield__label" for={inputId}>{label}</label>
  {/if}
  <div class="ui-textfield__wrapper" class:ui-textfield__wrapper--disabled={disabled}>
    <input
      id={inputId}
      class="ui-textfield__input"
      {type}
      {placeholder}
      {disabled}
      {readonly}
      bind:value
      {oninput}
      {onchange}
      aria-invalid={error || undefined}
      aria-describedby={helperText ? `${inputId}-helper` : undefined}
    />
  </div>
  {#if helperText}
    <p
      id="{inputId}-helper"
      class="ui-textfield__helper"
      class:ui-textfield__helper--error={error}
      class:ui-textfield__helper--normal={!error}
    >
      {helperText}
    </p>
  {/if}
</div>

<style>
  .ui-textfield {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    font-family: var(--ui-font-family, inherit);
  }
  .ui-textfield__label {
    font-size: var(--ui-tf-label-size, 0.8125rem);
    font-weight: 500;
    color: var(--ui-tf-label-color, #374151);
  }
  .ui-textfield__wrapper {
    display: flex;
    align-items: center;
    gap: 0.5em;
    height: var(--ui-tf-height, 2.5rem);
    padding: var(--ui-tf-padding, 0 0.75rem);
    font-size: var(--ui-tf-font-size, 0.875rem);
    background-color: var(--ui-tf-bg, transparent);
    border: 1px solid var(--ui-tf-border, #d1d5db);
    border-radius: var(--ui-tf-radius, 0.375rem);
    transition: border-color 150ms;
    box-sizing: border-box;
  }
  .ui-textfield__wrapper:focus-within {
    border-color: var(--ui-tf-focus-border, var(--ui-color-primary, #3b82f6));
    box-shadow: 0 0 0 1px var(--ui-tf-focus-border, var(--ui-color-primary, #3b82f6));
  }
  .ui-textfield__wrapper--disabled { opacity: 0.5; pointer-events: none; }
  .ui-textfield__input {
    flex: 1;
    border: none;
    outline: none;
    background: transparent;
    font: inherit;
    color: inherit;
    padding: 0;
    min-width: 0;
  }
  .ui-textfield__helper {
    font-size: 0.75rem;
    margin: 0;
  }
  .ui-textfield__helper--error { color: var(--ui-color-error, #ef4444); }
  .ui-textfield__helper--normal { color: var(--ui-tf-helper-color, #6b7280); }

  /* Size variants */
  .ui-textfield[data-size="xs"] { --ui-tf-height: 1.5rem; --ui-tf-font-size: 0.75rem; --ui-tf-padding: 0 0.375rem; --ui-tf-radius: 0.25rem; --ui-tf-label-size: 0.6875rem; }
  .ui-textfield[data-size="sm"] { --ui-tf-height: 2rem; --ui-tf-font-size: 0.8125rem; --ui-tf-padding: 0 0.5rem; --ui-tf-radius: 0.3125rem; --ui-tf-label-size: 0.75rem; }
  .ui-textfield[data-size="md"] { --ui-tf-height: 2.5rem; --ui-tf-font-size: 0.875rem; --ui-tf-padding: 0 0.75rem; --ui-tf-radius: 0.375rem; --ui-tf-label-size: 0.8125rem; }
  .ui-textfield[data-size="lg"] { --ui-tf-height: 3rem; --ui-tf-font-size: 1rem; --ui-tf-padding: 0 1rem; --ui-tf-radius: 0.5rem; --ui-tf-label-size: 0.875rem; }
  .ui-textfield[data-size="xl"] { --ui-tf-height: 3.5rem; --ui-tf-font-size: 1.125rem; --ui-tf-padding: 0 1.25rem; --ui-tf-radius: 0.625rem; --ui-tf-label-size: 1rem; }

  /* Variant: outlined */
  .ui-textfield[data-variant="outlined"] { --ui-tf-bg: transparent; --ui-tf-border: #d1d5db; }
  /* Variant: filled */
  .ui-textfield[data-variant="filled"] { --ui-tf-bg: #f3f4f6; --ui-tf-border: transparent; }
  /* Variant: underlined */
  .ui-textfield[data-variant="underlined"] .ui-textfield__wrapper {
    border: none;
    border-bottom: 1px solid var(--ui-tf-border, #d1d5db);
    border-radius: 0;
    background: transparent;
  }
  .ui-textfield[data-variant="underlined"] .ui-textfield__wrapper:focus-within {
    border-bottom-color: var(--ui-tf-focus-border, var(--ui-color-primary, #3b82f6));
    box-shadow: none;
  }

  /* Error state */
  .ui-textfield[data-error] .ui-textfield__wrapper {
    border-color: var(--ui-color-error, #ef4444);
  }
  .ui-textfield[data-error] .ui-textfield__wrapper:focus-within {
    border-color: var(--ui-color-error, #ef4444);
    box-shadow: 0 0 0 1px var(--ui-color-error, #ef4444);
  }
</style>

// ui/lit/src/inputs/TextField.ts
import { LitElement, html, css, nothing } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import type { SizeVariant } from '../core/types';

/**
 * `<ui-text-field>` — Text input with label, helper text, error state,
 * and multiple visual variants.
 *
 * @fires ui-input  - On every keystroke (detail: { value }).
 * @fires ui-change - On blur/committed change (detail: { value }).
 *
 * @example
 * ```html
 * <ui-text-field label="Email" placeholder="you@example.com" type="email"></ui-text-field>
 * ```
 */
@customElement('ui-text-field')
export class UiTextField extends LitElement {
  static styles = css`
    :host {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
      font-family: var(--ui-font-family, inherit);
    }

    .label {
      font-size: var(--ui-tf-label-size, 0.8125rem);
      font-weight: 500;
      color: var(--ui-color-text, #374151);
    }

    .wrapper {
      display: flex;
      align-items: center;
      gap: 0.5em;
      height: var(--ui-tf-height, 2.5rem);
      padding: var(--ui-tf-padding, 0 0.75rem);
      font-size: var(--ui-tf-font-size, 0.875rem);
      background: var(--ui-tf-bg, transparent);
      border: 1px solid var(--ui-tf-border, #d1d5db);
      border-radius: var(--ui-tf-radius, 0.375rem);
      transition: border-color 150ms;
      box-sizing: border-box;
    }

    :host([size='xs']) .wrapper { height: 1.5rem;  font-size: 0.75rem;   padding: 0 0.375rem; border-radius: 0.25rem; }
    :host([size='sm']) .wrapper { height: 2rem;    font-size: 0.8125rem; padding: 0 0.5rem;   border-radius: 0.3125rem; }
    :host([size='md']) .wrapper { height: 2.5rem;  font-size: 0.875rem;  padding: 0 0.75rem;  border-radius: 0.375rem; }
    :host([size='lg']) .wrapper { height: 3rem;    font-size: 1rem;      padding: 0 1rem;     border-radius: 0.5rem; }
    :host([size='xl']) .wrapper { height: 3.5rem;  font-size: 1.125rem;  padding: 0 1.25rem;  border-radius: 0.625rem; }

    :host([variant='filled']) .wrapper {
      background: var(--ui-tf-filled-bg, #f3f4f6);
      border-color: transparent;
    }
    :host([variant='underlined']) .wrapper {
      background: transparent;
      border-color: transparent;
      border-bottom-color: var(--ui-tf-border-color, #d1d5db);
      border-radius: 0;
    }

    .wrapper:focus-within {
      border-color: var(--ui-color-primary, #4f46e5);
      box-shadow: 0 0 0 1px var(--ui-color-primary, #4f46e5);
    }

    :host([error]) .wrapper {
      border-color: var(--ui-color-error, #dc2626);
    }
    :host([error]) .wrapper:focus-within {
      border-color: var(--ui-color-error, #dc2626);
      box-shadow: 0 0 0 1px var(--ui-color-error, #dc2626);
    }

    .wrapper--disabled {
      opacity: 0.5;
      pointer-events: none;
    }

    input {
      flex: 1;
      border: none;
      outline: none;
      background: transparent;
      font: inherit;
      color: inherit;
      padding: 0;
      min-width: 0;
    }

    .helper {
      font-size: 0.75rem;
      margin: 0;
    }
    .helper--error {
      color: var(--ui-color-error, #dc2626);
    }
    .helper--normal {
      color: var(--ui-color-text-secondary, #6b7280);
    }
  `;

  @property({ type: String, reflect: true }) variant: 'outlined' | 'filled' | 'underlined' = 'outlined';
  @property({ type: String, reflect: true }) size: SizeVariant = 'md';
  @property({ type: String }) label = '';
  @property({ type: String }) placeholder = '';
  @property({ type: Boolean, reflect: true }) disabled = false;
  @property({ type: Boolean, reflect: true }) readonly = false;
  @property({ type: Boolean, reflect: true }) error = false;
  @property({ type: String }) helperText = '';
  @property({ type: String }) type = 'text';
  @property({ type: String }) value = '';

  @query('input') private _input!: HTMLInputElement;

  private _uniqueId = `ui-text-field-${Math.random().toString(36).slice(2, 9)}`;

  private _onInput() {
    this.value = this._input.value;
    this.dispatchEvent(
      new CustomEvent('ui-input', {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      }),
    );
  }

  private _onChange() {
    this.value = this._input.value;
    this.dispatchEvent(
      new CustomEvent('ui-change', {
        detail: { value: this.value },
        bubbles: true,
        composed: true,
      }),
    );
  }

  render() {
    return html`
      ${this.label ? html`<label class="label" for=${this._uniqueId} part="label">${this.label}</label>` : nothing}
      <div class="wrapper ${this.disabled ? 'wrapper--disabled' : ''}" part="wrapper">
        <input
          id=${this._uniqueId}
          .type=${this.type}
          .value=${this.value}
          .placeholder=${this.placeholder}
          ?disabled=${this.disabled}
          ?readonly=${this.readonly}
          aria-invalid=${this.error}
          @input=${this._onInput}
          @change=${this._onChange}
          part="input"
        />
      </div>
      ${this.helperText
        ? html`<p class="helper ${this.error ? 'helper--error' : 'helper--normal'}" part="helper">${this.helperText}</p>`
        : nothing}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-text-field': UiTextField;
  }
}
