// ui/svelte/src/data-display/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    variant = 'elevated' as 'elevated' | 'outlined' | 'filled',
    interactive = false,
    onclick,
    header,
    children,
    footer,
  }: {
    variant?: 'elevated' | 'outlined' | 'filled';
    interactive?: boolean;
    onclick?: (e: MouseEvent) => void;
    header?: Snippet;
    children?: Snippet;
    footer?: Snippet;
  } = $props();

</script>

{#snippet content()}
  {#if header}
    <div class="ui-card-header">
      {@render header()}
    </div>
  {/if}
  {#if children}
    <div class="ui-card-content">
      {@render children()}
    </div>
  {/if}
  {#if footer}
    <div class="ui-card-actions">
      {@render footer()}
    </div>
  {/if}
{/snippet}

{#if interactive}
  <button type="button" class="ui-card ui-card--{variant} ui-card--interactive" {onclick}>
    {@render content()}
  </button>
{:else}
  <div class="ui-card ui-card--{variant}">
    {@render content()}
  </div>
{/if}

<style>
  .ui-card {
    display: flex;
    flex-direction: column;
    border-radius: var(--ui-card-radius, 0.75rem);
    overflow: hidden;
    font-family: var(--ui-font-family, inherit);
    color: var(--ui-card-color, inherit);
    transition: box-shadow 200ms, transform 100ms;
    box-sizing: border-box;
    width: 100%;
    text-align: inherit;
  }
  .ui-card--elevated {
    background-color: var(--ui-card-bg, #fff);
    box-shadow: var(--ui-shadow-sm, 0 1px 3px rgba(0,0,0,0.1),0 1px 2px rgba(0,0,0,0.06));
    border: none;
  }
  .ui-card--outlined {
    background-color: var(--ui-card-bg, #fff);
    box-shadow: none;
    border: 1px solid var(--ui-card-border-color, #e5e7eb);
  }
  .ui-card--filled {
    background-color: var(--ui-card-filled-bg, #f9fafb);
    box-shadow: none;
    border: none;
  }
  .ui-card--interactive { cursor: pointer; }
  .ui-card--interactive:hover { box-shadow: var(--ui-shadow-md); }

  .ui-card-header { padding: var(--ui-card-header-padding, 1rem 1rem 0); }
  .ui-card-content { padding: var(--ui-card-content-padding, 1rem); flex: 1; }
  .ui-card-actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: var(--ui-card-actions-padding, 0.5rem 1rem 1rem);
    justify-content: flex-end;
  }
</style>

// ui/lit/src/data-display/Card.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * `<ui-card>` — Card container with named slots for header, default, footer.
 *
 * @slot header  - Card header area.
 * @slot         - Card body / main content.
 * @slot footer  - Card footer area (actions, links).
 *
 * @example
 * ```html
 * <ui-card variant="elevated" interactive>
 *   <span slot="header">Title</span>
 *   <p>Body content here</p>
 *   <div slot="footer"><ui-button>OK</ui-button></div>
 * </ui-card>
 * ```
 */
@customElement('ui-card')
export class UiCard extends LitElement {
  static styles = css`
    :host {
      display: flex;
      flex-direction: column;
      border-radius: var(--ui-card-radius, 0.75rem);
      overflow: hidden;
      font-family: var(--ui-font-family, inherit);
      color: var(--ui-card-color, inherit);
      text-decoration: none;
      transition: box-shadow 200ms, transform 100ms;
      box-sizing: border-box;
    }

    :host([variant='elevated']) {
      background-color: var(--ui-card-bg, #fff);
      box-shadow: var(--ui-shadow-sm, 0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06));
    }
    :host([variant='outlined']) {
      background-color: var(--ui-card-bg, #fff);
      border: 1px solid var(--ui-color-border, #e2e8f0);
      box-shadow: none;
    }
    :host([variant='filled']) {
      background-color: var(--ui-card-filled-bg, #f9fafb);
      box-shadow: none;
    }

    :host([interactive]) {
      cursor: pointer;
    }
    :host([interactive]:hover) {
      box-shadow: var(--ui-shadow-md, 0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06));
      transform: translateY(-1px);
    }

    .header {
      padding: var(--ui-card-header-padding, 1rem 1rem 0);
    }
    .body {
      padding: var(--ui-card-content-padding, 1rem);
      flex: 1;
    }
    .footer {
      padding: var(--ui-card-actions-padding, 0.5rem 1rem 1rem);
      display: flex;
      align-items: center;
      gap: 0.5rem;
      justify-content: flex-end;
    }
  `;

  @property({ type: String, reflect: true }) variant: 'elevated' | 'outlined' | 'filled' = 'elevated';
  @property({ type: Boolean, reflect: true }) interactive = false;

  render() {
    return html`
      <div class="header" part="header"><slot name="header"></slot></div>
      <div class="body" part="body"><slot></slot></div>
      <div class="footer" part="footer"><slot name="footer"></slot></div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-card': UiCard;
  }
}
