// ui/angular/src/layout/Grid.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
} from '@angular/core';

/**
 * Grid — Standalone Angular component.
 * CSS Grid layout with configurable columns, rows, and gap.
 *
 * @example
 * ```html
 * <ui-grid [columns]="3" gap="16px">
 *   <div>Cell 1</div>
 *   <div>Cell 2</div>
 *   <div>Cell 3</div>
 * </ui-grid>
 * ```
 */
@Component({
  selector: 'ui-grid',
  standalone: true,
  imports: [],
  template: `
    <div
      class="ui-grid"
      [style.gridTemplateColumns]="columnsTemplate()"
      [style.gridTemplateRows]="rows()"
      [style.gap]="gap()"
    >
      <ng-content />
    </div>
  `,
  styles: [`
    :host { display: block; }
    .ui-grid {
      display: grid;
      box-sizing: border-box;
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Grid {
  readonly columns = input<number | string>(12);
  readonly rows = input<string>('');
  readonly gap = input('var(--ui-space-3, 12px)');

  columnsTemplate(): string {
    const c = this.columns();
    if (typeof c === 'number') {
      return `repeat(${c}, 1fr)`;
    }
    return c;
  }
}

// ui/lit/src/layout/Grid.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

/**
 * `<ui-grid>` — CSS Grid layout container.
 *
 * @slot - Grid children.
 *
 * @example
 * ```html
 * <ui-grid columns="3" gap="16px">
 *   <div>Cell 1</div>
 *   <div>Cell 2</div>
 *   <div>Cell 3</div>
 * </ui-grid>
 * ```
 */
@customElement('ui-grid')
export class UiGrid extends LitElement {
  static styles = css`
    :host {
      display: grid;
      box-sizing: border-box;
    }
  `;

  @property({ type: String }) columns = '1';
  @property({ type: String }) gap = '0';
  @property({ type: String }) rows = '';

  updated(): void {
    // If columns is a plain number, convert to repeat(N, 1fr)
    const cols = /^\d+$/.test(this.columns)
      ? `repeat(${this.columns}, 1fr)`
      : this.columns;
    this.style.gridTemplateColumns = cols;
    this.style.gap = this.gap;
    if (this.rows) {
      const r = /^\d+$/.test(this.rows)
        ? `repeat(${this.rows}, 1fr)`
        : this.rows;
      this.style.gridTemplateRows = r;
    }
  }

  render() {
    return html`<slot></slot>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'ui-grid': UiGrid;
  }
}
